### ISSUE TITLE
fix LinearPruning constructor

### ISSUE THREAD

**Issue by malb** [fplll/fplll#108]
The LinearPruning constructor currently lies about the success probability. This should be fixed once the pruner is included which allows to compute said probability.

**Comment by malb** [comment]
It seems the Pruner API doesn't make this straight forward yet.

What I'd want is a function `svp_probability` which takes a set of pruning coefficients and returns the success probability. The function currently available, though, relies on a particular basis being loaded to set up `d` and `n` and potentially other internal variables (?)

@lducas any recommendations?

**Comment by cr-marcstevens** [comment]
You also need radius and r_sq_norms besides pruning coefficients to be able to compute success probability.
But maybe a struct containing such basic data and non-pruning functions that compute success probability and estimated cost can be put into a base class that can be used for all PrunerVariants.

**Comment by lducas** [comment]
As far as I can tell (i.e., just a brief look at the code, not having
tested) the function svp_probability doesn't require a basis to have been
loaded, as its result does not depends on the basis.

As for needing radius and r_sq_norms for computing them, well, it all
depends. They are not needed to compute the success probability when
success is define as ``what is found is the shortest vector'', but they are
when success means `` something will be found''.

While the code written before integration into fplll offered both, so far,
only the first option for the def of success is implemented. In the long
run I'd like to have both using flags and so and so. The conclusion is that
I would like to keep this function inside the class, even though it doesn't
really use the variables of the class in the current version. In later
version it will.

Is this satisfactory @malb ?

Cheers


2016-07-15 16:38 GMT+02:00 cr-marcstevens <notifications@github.com>:

**Comment by malb** [comment]
I'm fine with keeping a function as a method of the class.

Perhaps one of the following two options would be good, though:

1. we offer a frontend function `svp_probability` which sets up an instance of the pruner class correctly? For example, at the moment, the only way to set `n` and `d` is to load a basis. 

2. outsource some helper functions to functions and then just call those directly in a function `svp_probability`?

**Comment by lducas** [comment]
Sure. If urgent (i.e. wanted before  weeks), feel free to proceed.
Otherwise you can assign it to me.

-- L

2016-07-18 17:53 GMT+02:00 Martin Albrecht <notifications@github.com>:

**Comment by malb** [comment]
I'd say this is a blocker for the release, but we're not in a hurry with that either. I'll see what I can do in the meantime.

**Comment by lducas** [comment]
I'm implementing your solution 1. Solution 2 requires pulling half of the code of the pruner out of the class (not sure what is best in the long run though).

**Comment by lducas** [comment]
I'm having trouble naming the external function as the internal one (svp_probability). For now, the external function is called svp_probability2. See pull request to come. Do you have a better suggestion ?

**Comment by malb** [comment]
Sorry, only saw your comment after I fixed up the code. I addressed the issue by using the namespace explicitly.
