### ISSUE TITLE
Functions (sqrt/log) on dd_reals

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#115]
The ``easy'' interface to \<NR_FP\<FT\>\> fails when FT = dd_real (but works well with double, long double and mpfr_t).

The following error is raised when uncommenting the line 245 in tests/test_pruner.cpp (currently under pull request from https://github.com/lducas/fplll):
``
test_pruner.o: In function `fplll::Pruner<fplll::FP_NR<dd_real> >::load_basis_shape(int, double*)':
test_pruner.cpp:(.text._ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd[_ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd]+0x95): undefined reference to `log(dd_real const&)'
test_pruner.cpp:(.text._ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd[_ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd]+0x267): undefined reference to `exp(dd_real const&)'
test_pruner.cpp:(.text._ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd[_ZN5fplll6PrunerINS_5FP_NRI7dd_realEEE16load_basis_shapeEiPd]+0x623): undefined reference to `sqrt(dd_real const&)'
``

**Comment by shi-bai** [comment]
Hi Leo,

I just tried your fplll fork from https://github.com/lducas/fplll. Is it the same as the pull request?

I added the line
test_pruner_LDADD=-lgmp -lmpfr $(LIBQD_LIBADD)
to Makefile.am in test/ folder. Then the make check works with enabling the line:
  status |= test_unpruned<FP_NR<dd_real> >(); 

results are:
PASS: test_nr
PASS: test_pruner
PASS: test_svp
PASS: test_lll
PASS: test_bkz
make[4]: Entering directory '/home/shi/suite/leo_fplll/tests'

Shi

**Comment by lducas** [comment]
Thanks !
