### ISSUE TITLE
Missing overloaded operators for NR_FP

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#126]
Currently, a few natural operation like x - 1 don't compiles because NR_FP - double is not implemented. 

Once added, a dirty hack in pruner.h should be removed (creation and use  of a ``variable'' FT one = 1;).

**Comment by lducas** [comment]
Ideally, a ``read_from_string'' function for NR_FP would be nice as well. Another hack could be removed in pruner.h.

**Comment by malb** [comment]
The first issue is solved in https://github.com/fplll/fplll/pull/122/commits/e5f13a7d3483f72d638c1b1693b31666a8361218
