### ISSUE TITLE
should rerandomization set clean flag?

### ISSUE THREAD

**Issue by blowfish880** [fplll/fplll#128]
the rerandomization called at https://github.com/fplll/fplll/blob/master/fplll/bkz.cpp#L331 runs LLL once it is done, but it is not checked if LLL caused any progress. isn't it possible that by pure chance LLL improves the first vector of a block after rerandomization, even if the randomization is restricted to the tail of the block? 

furthermore, just as in https://github.com/fplll/fplll/blob/master/fplll/bkz.cpp#L317, LLL should probably be started at the beginning of the basis rather than the block, for the same reason as this: https://github.com/fplll/fplll/issues/111.

finally, i think there is a corner case where svp_reduction calls enumeration on an unreduced block, that being: 1) we're in the k-th loop in the svp-reduction with k > 1; and 2) the (k-1)th loop found a short vector and the vector found was already in the basis (but not the first one). in this case the svp post processing is called and only moves the vector to the front, but does not call LLL afterwards. the rerandomization in the k-th loop is skipped (as it should - we already changed the basis), but that means that LLL is not called before we rerun enumeration, which unsurprisingly can lead to problems in the enumeration. there are two possible fixes for that: either call LLL after the post processing no matter what, or move the LLL call from the rerandomization into the loop of svp reduction (after the if(randomize) block). the latter would get rid of the LLL call before the for loop in svp reduction.

**Comment by malb** [comment]
LLL after rerandomisation should only touch kappa+1 to kappa + block_size, right, to make sure we don't screw up `clean` just because we reranomised. So https://github.com/fplll/fplll/blob/master/fplll/bkz.cpp#L163 should start at `min_row` Does that make sense?

Moving the LLL call unconditionally to the front of the loop (and starting at `kappa`) means we could terminate on `clean` any more, right because after rerandomisation LLL will always have something to do. Maybe running LLL unconditionally after we found a vector instead?

Doesn't #111 say we should start LLL at the beginning of the block instead of at the beginning of the basis?

**Comment by blowfish880** [comment]
but how does the rerandomisation ensure that the block we are going to enumerate on is LLL reduced if it is not allowed to touch the first vector? the LLL call, while started on kappa+1, is allowed to touch previous vectors since kappaMin is 0, no?

i agree, moving the LLL call into the loop would not allow us to set the clean flag depending on the number of swaps performed during LLL. rather, one would have to check if the first vector was changed (by storing a copy, using transformation matrix, or just checking the length). might be a more sensible approach anyway, since even now we could have false negatives on the first call. 

i think, https://github.com/fplll/fplll/issues/111 says, that the parameters kappaMin and kappaStart for the lll call should actually be the same (damien noticed some numerically unstable behavior if they are not), be it 0 (the default behavior) or kappa (the bounded_lll flag).

**Comment by malb** [comment]
Okay, setting `clean` only depending on whether we improved the first vector seems like the right thing™ and would simplify the code, too. Also, +1 for syncronising `kappa_min` and `kappa_start`.

**Comment by malb** [comment]
This is resolved.
