### ISSUE TITLE
Pruning constructor

### ISSUE THREAD

**Issue by malb** [fplll/fplll#141]
Shall we add a constructor for the `Pruner` which takes all the standard parameters and assigns them?

```
  Pruner<FP_NR<double>> pru;
  pru.enumeration_radius   = enumeration_radius;
  pru.target_probability = target_probability;
  pru.preproc_cost         = preproc_cost;
  pru.load_basis_shape(m, start_row, end_row);
  pru.optimize_coefficients(pr);
  probability = pru.svp_probability(pr);
```

looks strange.

**Comment by cr-marcstevens** [comment]
Are there use cases for calling pruner without specifying enumeration_radius, target_prob and preproc_cost ?

Why not a constructor like?:
Pruner(FT enumeration_radius, FT preproc_cost = 0, FT target_prob = 0.9)
