### ISSUE TITLE
-Wdelete-non-virtual-dtor

### ISSUE THREAD

**Issue by malb** [fplll/fplll#150]
I'm getting this error when building fpylll

```
deleting object of polymorphic class type ‘fplll::Enumeration<fplll::FP_NR<double> >’ which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
```

any suggestions?

**Comment by cr-marcstevens** [comment]
See:
http://stackoverflow.com/questions/461203/when-to-use-virtual-destructors

This is a special issue that isn't a problem for the way we use base and derived classes for enumeration.

But to solve this warning-error:
We need to declare the destructor of the base class (here enumeration_base) virtual, so when delete'ing a derived object via a pointer to its base class it will be handled properly and the destructor for the derived object gets called.

On July 19, 2016 10:39:39 PM GMT+02:00, Martin Albrecht <notifications@github.com> wrote:
>I'm getting this error when building fpylll
>
>```
>deleting object of polymorphic class type
>‘fplll::Enumeration<fplll::FP_NR<double> >’ which has non-virtual
>destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
>```
>
>any suggestions?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fplll/fplll/issues/150

-- sent from phone

**Comment by malb** [comment]
Thanks!
