### ISSUE TITLE
option for not compiling libfplll

### ISSUE THREAD

**Issue by shi-bai** [fplll/fplll#160]
The libtool seems to take a long time for compiling libfplll. In developing or debugging, each time making some changes and recompile, I have to wait for about ten secs on my laptop to wait for the compilation. It seems that libtool part can not be speeded-up by make -jN.  Thus I would prefer if there is an option in makefile.am to control whether we are compiling fplll as a library; or just compiling the binaries. The later could be useful in development stages. I could assign this to myself -- would like to see if everyone is happy with such feature (or dislike) :)

**Comment by malb** [comment]
Mhh, are you sure it's actually libfplll which is killing performance, i.e. wouldn't you have the same problem also for the binary? If so, which step is slow? Is it linking? Maybe we can do something about it?

In any case, `--disable-libfplll` wouldn't hurt, so no objection :) I'm mainly trying to see if we can solve the problem instead of working around it.

**Comment by cr-marcstevens** [comment]
I believe this problem is best solved via make targets, which already exist.
I.e., if you go into dir fplll and do 'make fplll' it should do the minimal (re-)compilation to build fplll.
Just 'make' builds the first target in Makefile, typically a 'all' target that compiles everything.

But I've you look at this latest line when building:

/bin/sh ../libtool  --tag=CXX   --mode=link g++-5.3.0 -std=c++11  -O3 -Wall   -o fplll main.o libfplll.la -lmpfr -lmpfr -lgmp -lgmp

Then it seems you actually need to compile the library to build the executables?

-- Marc

**Comment by shi-bai** [comment]
On Sun, Jul 24, 2016 at 1:57 PM, cr-marcstevens <notifications@github.com>
wrote:

> I believe this problem is best solved via make targets, which already
> exist.
> I.e., if you go into dir fplll and do 'make fplll' it should do the
> minimal (re-)compilation to build fplll.
> Just 'make' builds the first target in Makefile, typically a 'all' target
> that compiles everything.
>
> But I've you look at this latest line when building:
>
> /bin/sh ../libtool --tag=CXX --mode=link g++-5.3.0 -std=c++11 -O3 -Wall -o
> fplll main.o libfplll.la -lmpfr -lmpfr -lgmp -lgmp
>
> Then it seems you actually need to compile the library to build the
> executables?
>
I think libfplll is pretty much used everywhere in compiling the
executables by looking into makefile.am. Thus a change of, e.g. nr/lll/bkz
will trigger a change of libfplll.



> -- Marc
>
> On 2016-07-24 13:31, Martin Albrecht wrote:
> > Mhh, are you sure it's actually libfplll which is killing performance,
> i.e. wouldn't you have the same problem also for the binary? If so, which
> step is slow? Is it linking? Maybe we can do something about it?
>
> That is a good catch, I just tried,

time make -j4

real 2m42.623s
user 8m56.152s
sys 0m8.052s

It seems that the following compiling step is slow, e.g.

libtool: compile:  g++ -std=c++11 -DHAVE_CONFIG_H -I. -I..
-DFPLLL_DEFAULT_STRATEGY_PATH=\"/usr/local/share/fplll/strategies\"
-DFPLLL_DEFAULT_STRATEGY=\"/usr/local/share/fplll/strategies/default.json\"
-O3 -Wall -MT sieve/sieve_gauss_3sieve.lo -MD -MP -MF
sieve/.deps/sieve_gauss_3sieve.Tpo -c sieve/sieve_gauss_3sieve.cpp  -fPIC
-DPIC -o sieve/.libs/sieve_gauss_3sieve.o

The last step linking seems fast:
libtool: link: g++ -std=c++11 -O3 -Wall -o .libs/latsieve
sieve/sieve_main.o  ./.libs/libfplll.so /usr/local/lib/libqd.so
/usr/local/lib/libmpfr.so /usr/local/lib/libgmp.so

For the moment, I am not sure why the compilation could be so slow. I used
cmake personally for a previously version (prioir BKZ 2.0) of fplll and
time make -j4

real 0m21.679s
user 1m20.188s
sys 0m2.720s

Let me check this more and get back to you  :)

Cheers,
Shi

**Comment by shi-bai** [comment]
I have checked the compilation time for each step: it seems that enumeration and sieve are time-consuming. I added a optional makefile.am.nolib in pull request https://github.com/fplll/fplll/pull/166 which only compiles fplll using the sources (but not the lib file).  Now it takes about 40 secs with make -j4. It seems that this is close to the best we can do. Or perhaps with -O2 it reduces a bit.

Cheers,
Shi

**Comment by malb** [comment]
Why is it faster to build sieving for fplll the binary than for fplll the lib?

To be honest, I think having two `Makefile.am` files is a recipe for disaster. Why not create an alternative make target in the same `Makefile.am` instead of copy'n' pasting?

**Comment by shi-bai** [comment]
I mean the following flow: libfplll --> fplll seems slow. Instead, not building the library libfplll, but directly building the binary fplll directly seems faster. 

Building sieving is slow. Previously I didn't make it build by default. But the current version build it by default due to the make check for sieve.

I tried to have another target (also tried to use a conditioning) in Makefile.am (and configure.ac). However, there is some problem due to the following:
https://www.gnu.org/software/automake/manual/html_node/Objects-created-both-with-libtool-and-without.html

I don't know how to solve it.

Cheers,
Shi

**Comment by malb** [comment]
Okay, I think I understand the problem now. When we touch, say, `bkz.h` this triggers a rebuild of sieving because that includes `fplll.h` which in turn includes `bkz.h`. Building sieving is slow. What I suggest we do:

1. don't include `fplll.h` anywhere in our internal code, but include the right headers directly. That means moving some highlevel functions from `fplll.cpp` to `lll.cpp`. This will lead to sieving not being rebuild when BKZ is worked on.

2. (optional) create a separate shared library for sieving `libfplllsieve.so` which includes the sieving code  so that we can do `make fplll` without triggering a sieving build.

I'll get started with 1.

**Comment by shi-bai** [comment]
Hi Martin,

Thanks for looking at it. I think for latsieve; perhaps we could just not compile it by default for the moment, as it is not used in fplll.cpp. 

On the other hand, the library compilation seems to be slow (not regarding sieve). I compared using the other makefile from https://github.com/fplll/fplll/edit/minimal_makefile/fplll/Makefile.am.nolib?pr=/fplll/fplll/pull/166

and use the current makefile with only fplll and libfplll enabled. 

The first one (without libfplll) is still about twice faster. 

Cheers,
Shi

**Comment by malb** [comment]
I just created #168 

## master

```
$ touch bkz.h && time make V=0 fplll
  CXX      main.o
  CXX      fplll.lo
  CXX      bkz.lo
  CXX      sieve/sieve_gauss.lo
  CXX      sieve/sieve_gauss_2sieve.lo
  CXX      sieve/sieve_gauss_3sieve.lo
  CXX      sieve/sieve_gauss_4sieve.lo
  CXX      sieve/sampler_basic.lo
  CXXLD    libfplll.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    fplll
make V=0 fplll  77.35s user 2.18s system 99% cpu 1:20.07 total
```

## 168

```
$ touch bkz.h && time make V=0 fplll
  CXX      main.o
  CXX      fplll.lo
  CXX      bkz.lo
  CXXLD    libfplll.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    fplll
make V=0 fplll  10.92s user 0.40s system 97% cpu 11.564 total
```

```
touch wrapper.h && time make V=0 fplll
  CXX      main.o
  CXX      fplll.lo
  CXX      wrapper.lo
  CXX      bkz.lo
  CXX      sieve/sieve_gauss.lo
  CXXLD    libfplll.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    fplll
make V=0 fplll  18.67s user 0.74s system 98% cpu 19.763 total
```

**Comment by shi-bai** [comment]
Thanks Martin. It's a very nice commit 168 :) I could repeat above.  Here are some timings

==============
A full build
==============
time make -j8 V=0 
  CXX      fplll.lo
  CXX      util.lo
  CXX      lll.lo
  CXX      wrapper.lo
  CXX      bkz.lo
  CXX      bkz_param.lo
  CXX      gso.lo
  CXX      pruner.lo
  CXX      main.o
  CXX      latticegen.o
  CXX      sieve/sieve_main.o
  CXX      enum/topenum.lo
  CXX      enum/enumerate.lo
  CXX      enum/enumerate_base.lo
  CXX      enum/evaluator.lo
  CXX      sieve/sieve_gauss.lo
  CXX      sieve/sieve_gauss_2sieve.lo
  CXX      sieve/sieve_gauss_3sieve.lo
  CXX      sieve/sieve_gauss_4sieve.lo
  CXX      sieve/sampler_basic.lo
  CXXLD    libfplll.la
  CXXLD    fplll
  CXXLD    latticegen
  CXXLD    latsieve
real	1m2.282s
user	2m42.992s
sys	0m3.500s

==============
A change in bkz 
==============
 touch bkz.h && time make -j8 V=0 fplll
  CXX      main.o
  CXX      fplll.lo
  CXX      bkz.lo
  CXXLD    libfplll.la
  CXXLD    fplll
real	0m9.305s
user	0m12.932s
sys	0m0.468s

==============
and above without compiling lib
==============
touch bkz.h && time make -j8 V=0 fplll
  CXX      main.o
  CXX      fplll.o
  CXX      bkz.o
  CXXLD    fplll
real	0m4.672s
user	0m7.216s
sys	0m0.228s

This would very useful for developing! I merge commit 168 and close this ticket.

Cheers,
Shi

**Comment by malb** [comment]
Can you try with -j1 ? We should try to understand what makes compiling
libfplll more expensive.  Linking itself take 0.5 seconds on my local
machine. Maybe compiling bzk_reducition in bkz.cpp is just sequential, but
compiling it in fplll.cpp allows to parallelise with bkz.cpp.

**Comment by shi-bai** [comment]
Hi Martin,

It seems to me that (also from above tests) that compiling the library  is slow than compiling the binaries. To double check this, I just compared the following two makefile.am(s).

Then I do a  time make V=0

------------------------------------------------------------------------
For compiling the lib, and then link fplll with the lib, I got,
  CXX      fplll.lo
  CXX      util.lo
  CXX      enum/topenum.lo
  CXX      enum/enumerate.lo
  CXX      enum/enumerate_base.lo
  CXX      enum/evaluator.lo
  CXX      lll.lo
  CXX      wrapper.lo
  CXX      bkz.lo
  CXX      bkz_param.lo
  CXX      gso.lo
  CXX      pruner.lo
  CXXLD    libfplll.la
  CXXLD    fplll
real	2m58.392s
user	2m54.496s
sys	0m3.548s

------------------------------------------------------------------------
For not compiling the lib, I got,
  CXX      main.o
  CXX      fplll.o
  CXX      util.o
  CXX      enum/topenum.o
  CXX      enum/enumerate.o
  CXX      enum/enumerate_base.o
  CXX      enum/evaluator.o
  CXX      lll.o
  CXX      wrapper.o
  CXX      bkz.o
  CXX      bkz_param.o
  CXX      gso.o
  CXX      pruner.o
  CXXLD    fplll

real	1m30.043s
user	1m28.164s
sys	0m1.716s


[Makefile.am_lib.txt](https://github.com/fplll/fplll/files/382390/Makefile.am_lib.txt)
[Makefile.am_nolib.txt](https://github.com/fplll/fplll/files/382389/Makefile.am_nolib.txt)




1.

**Comment by shi-bai** [comment]
Following above, with the current Makefile.am in github, I did a full compile with 

time make V=0 

-----------------------------------------------------------------------------------

  CXX      fplll.lo
  CXX      util.lo
  CXX      enum/topenum.lo
  CXX      enum/enumerate.lo
  CXX      enum/enumerate_base.lo
  CXX      enum/evaluator.lo
  CXX      lll.lo
  CXX      wrapper.lo
  CXX      bkz.lo
  CXX      bkz_param.lo
  CXX      gso.lo
  CXX      pruner.lo
  CXX      sieve/sieve_gauss.lo
  CXX      sieve/sieve_gauss_2sieve.lo
  CXX      sieve/sieve_gauss_3sieve.lo
  CXX      sieve/sieve_gauss_4sieve.lo
  CXX      sieve/sampler_basic.lo
  CXXLD    libfplll.la
  CXX      main.o
  CXXLD    fplll
  CXX      latticegen.o
  CXXLD    latticegen
  CXX      sieve/sieve_main.o
  CXXLD    latsieve

real	3m18.251s
user	3m12.708s
sys	0m4.900s

It seems that enum/enumerate_base.lo take about 1 min. The other steps take more or less similar time.

Cheers,
Shi

**Comment by malb** [comment]
Hi, not sure I follow. So the difference is due to enumeration_base ?
Otherwise, I guess we should time the steps to find out why one is faster
than the other.

typed with thumbs, please excuse my brevity

**Comment by shi-bai** [comment]
For the "real 3m18.251s" test, I used the current Makefile.am. I meant for the current git version fplll code, compiling "enum/enumerate_base.lo" is the bottleneck, as it takes one third (1 minute) of the total compiling time. All the other steps take 5-10 secs.

For the other two tests,  it seems that [compiling the fplll binary directly] (not generating libfplll) is faster than [compiling the libfplll first and then compile-link to fplll].

Anyway, the last  #168 is quite nice for me and I am happy with its current status :)

**Comment by malb** [comment]
The reason for the performance difference is that libtool builds everything twice (make V=1 shows it), once for the static and once for the dynamic library, cf. https://stackoverflow.com/questions/572760/libtool-slowness-double-building

If you want to avoid this double build time you can run `/configure --disable-static` which disables building the static library. If you want, we can add something to this effect to CONTRIBUTING.md, but other than that, I'd say this issue is resolved (?)

**Comment by shi-bai** [comment]
Good for me. We could close the ticket.

Shi
