### ISSUE TITLE
--march=native -O3

### ISSUE THREAD

**Issue by malb** [fplll/fplll#170]
Compiling with `--march=native -O3` as per #169 leads to:

```
./test_bkz
terminate called after throwing an instance of 'std::runtime_error'
  what():  infinite loop in babai
[1]    8061 abort      ./test_bkz
```

on my machine.

**Comment by shi-bai** [comment]
I could repeat this. It looks like coming from the sdb reduction:

 fplll/fplll -a sdb -b 10 tests/lattices/dim55_in 
Warning: SD Variant of BKZ requires explicit termination condition. Turning auto abort on!
terminate called after throwing an instance of 'std::runtime_error'
  what():  infinite loop in babai
Aborted

**Comment by malb** [comment]
Let's assign to @blowfish880  ;)

**Comment by blowfish880** [comment]
Sorry, I only just saw that I should probably look at this (when I see a compiler flag in the title I automatically assume this doesn't concern me...). I'm on it.

**Comment by blowfish880** [comment]
i'm having trouble reproducing this. i do the following on the current version of the master branch:
```
CXXFLAGS='-march=native -O3' ./configure
make clean
make
make check
```
all checks, including the bkz test, pass. am i not compiling this right?

**Comment by malb** [comment]
This looks right. Maybe it isn't a problem on your architecture?  I'm on Intel i7, gcc (Debian 5.4.0-6) 5.4.0 20160609

Do you have another system to try?

**Comment by blowfish880** [comment]
i have now tried the following configurations:
- Intel i5-5200U, Ubuntu 16.04, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)
- Intel i7-2600, Ubuntu 14.04, clang version 3.4-1ubuntu3
both of them seem to work fine. these are the only two systems i have available.

**Comment by malb** [comment]
I now also tried with GCC 6.0 and get the same error. I'll try on a different machine as well.

**Comment by tlepoint** [comment]
Fyi, couldn't reproduce either with Apple Clang 8.0.0 on Intel Core m7.

**Comment by shi-bai** [comment]
I tried to debug this a while ago but failed to identify the exact reason.

I tend to believe now there is no bug. The dim55_in lattice is already bad for numerical purpose such that the LLL does not work in double. See http://perso.ens-lyon.fr/damien.stehle/FPLLL.html. 

Thus I could accept that the sdb fails with double. With large precision, it works
fplll/fplll -a sdb -b 10 -f dd tests/lattices/dim55_in

**Comment by zhli271828** [comment]
So how to deal with this bug now?
I'm using sage bkz.

`terminate called after throwing an instance of 'std::runtime_error'
  what():  infinite loop in babai`

**Comment by malb** [comment]
I don't think your problem has anything to do with this ticket as Sage doesn't use `--march=native -O3` You'll want to increase precision either by switching to a different floating point type or by increasing the precision used by mpfr. See #244

**Comment by zhli271828** [comment]
When I use `M.BKZ(proof=False)` or `M.BKZ(fp='fp', proof=False)`, it outputs this error.
`M.BKZ(fp='ld', proof=False)` works for me.
Thanks.
