### ISSUE TITLE
Buggy (call to ?) get_r

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#174]
Adding the line 
`  cerr << "RAD " << radius << endl;`
just after
`M.get_r(radius, 0, 0);`
at line 279 of tests/test_pruner.cpp

I uncovered extremely strange behavior of get_r. I obtain a value equal to n  (and this messes up the call to prune).

Any idea what could be happening ?

**Comment by malb** [comment]
The first line of `A` there is

```
[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
``` 

so the output seems right (?)

**Comment by lducas** [comment]
Indeed Martin...
@dstehle youchange gen_ntrulike recently. Is this behavior intended ?
