### ISSUE TITLE
 bkz_reduction function with IntMatrix elements of size greater than 64 bits 

### ISSUE THREAD

**Issue by Vaggelis1994** [fplll/fplll#176]
Hello dear Developers,

I am currently developing an algorithm for my [thesis project](https://eprint.iacr.org/2012/620.pdf) using the function of `bkz_reduction`. In the link there is a short description of how the matrix is constructed and how a solution should be found. 

For example, in order for a solution to be exported the first row of the bkz_reduced matrix should be for the first n elements all of type **|b_i| = 1** and the last three should be like **b_n+1 = 0, |b_n+2| = 1** and **b_n+3 = 0**.

The matrix B is of size **(n+1)x(n+3)** and it contains `Integer` elements, as it should be. Some of them, a specific column actually, are of n bits size. 

When applying the `bkz_reduction` function at **n<64** size, the algorithm behaves as expected and the results are as expected! On the contrast, when the size of **n** is larger or equal to that of 64 there are not any expected results.

I am not quite sure, but I am assuming that this might happens because of the limits (greatest values) of some of the data types used or even because of my (64 bits) computer architecture.

What I would like to know is whether you may have a possible explanation for this issue, and if so, I would like to know if there is a possible solution to that.

I provide the file with the code, hoping that you may be able to check the problematic behavior you, as well. Moreover, if I am not explaining the issue properly, I could happily elaborate more. 

In order to execute the code, you can compile it and run it as below:

` g++ -O3 -std=c++11 main.cpp -o bkz -lfplll -lqd -lmpfr -lgmp`
`./bkz 60`
`./bkz 64`

The first execution `./bkz 60` will generate a solution and print a corresponding message. On the other hand, the second execution `./bkz 64` will probably fail and will probably keep searching for a solution within the range of all the different blocksizes. Hopefully, I would like to make this code work for dimension of size **n=80**. 

Thanking in advance for your assistance.

**Comment by blowfish880** [comment]
Hi Vaggelis1994,

I'm afraid none of us will have the time to dig through your code and the paper you linked to. Could you be a little more specific about the basis you are handing to fpLLL, what you are trying to do with it, what you are expecting, and what you are getting? Are there any error messages? Ideally, you would generate a specific basis, and tell us which invocation of fpLLL does not return the expected result.

**Comment by malb** [comment]
Just to clarify: fplll's BKZ should handle integer entries that a bigger than machine words, i.e. bigger than 64 bits. So there's a bug somewhere in your set up code or in fplll.

**Comment by Vaggelis1994** [comment]
Just to make it clear, the issue was the numbers used for the initialization of the Matrix. I was producing double numbers from C++ built-in routines and assigned them to mpz_t variables. Thus, the precision was not as affective as it should have been and the results were problematic. 

Thank you both for your replies. You may close the issue.
