### ISSUE TITLE
Release: no autogen.sh but automaker 1.14?

### ISSUE THREAD

**Issue by tlepoint** [fplll/fplll#180]
In the release, the aclocal.m4 file is generated from autoconf-1.14

```
# generated automatically by aclocal 1.14.1 -*- Autoconf -*-

...
```

I have autoconf-1.15, which means that if I modify configure.ac, I cannot build anymore.

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /[XXX]/fplll-5.0.0/missing aclocal-1.14 -I m4
/[XXX]/fplll-5.0.0/missing: line 81: aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127

```

Can something be done about that (I'm not sure)? Why is autogen.sh removed from the release?

**Comment by malb** [comment]
I figured the release comes with `configure` so we don't need `autogen.sh`, which was only added because people cannot remember `autoreconf -i` IIRC. I'm not opposed to including it, though. I view the release as "build and use" and a git checkout as "develop".

**Comment by tlepoint** [comment]
Ok, that sounds good to me! No need to add it then 👍
