### ISSUE TITLE
lib tool: warning -no-install

### ISSUE THREAD

**Issue by tlepoint** [fplll/fplll#181]
On x86_64-apple-darwin15.6.0, when I run `make check`, I get

```
libtool: warning: '-no-install' is ignored for x86_64-apple-darwin15.6.0
libtool: warning: assuming '-no-fast-install' instead
```

**Comment by malb** [comment]
Not sure if there's much we could do (except for checking for OSX manually). We pass `-no-install` so we can `gdb ./test_foo` cf. 

> -no-install  
> Link an executable output-file that can’t be installed and therefore doesn’t need a wrapper script on 
> systems that allow hardcoding of library paths. Useful if the program is only used in the build tree, e.g., > for testing or generating other files.

https://www.gnu.org/software/libtool/manual/html_node/Link-mode.html

Does it produce any problems?

**Comment by tlepoint** [comment]
No it does not, it was just fyi.

**Comment by malb** [comment]
Okay, closing it then. Thanks!
