### ISSUE TITLE
Forgotten soname bump

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#185]
The new release has the same soname as the previous one even though the api are completely incompatible : there should have been a bump.

**Comment by malb** [comment]
Ah, crap. Any suggestion from the top of your head how to bump it most elegantly from auto tools?

**Comment by SnarkBoojum** [comment]
I had a quick look ; the good side is that you use libtool, which is supposed to make it easy. The bad side is that a correspondance between the project version and the library version is engraved in the code : look at the sentence starting with **never** in libtool's [documentation](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html#Updating-version-info).

I'll try to have a look tomorrow. Or, well, let's say today after my night.

**Comment by malb** [comment]
Thanks! I'm somewhat tempted to just use the `-release` flag, which seems to be fine for a research heavy library (?) But also happy to do this right (although this increases the risk of us forgetting again in the future)

**Comment by malb** [comment]
Okay, created pull request #186 which hopefully resolves this. Let me know if this is okay. If so, we'll cut a 5.0.1 release with this.

**Comment by SnarkBoojum** [comment]
It looks good, thanks!
