### ISSUE TITLE
README: differentiate building from source and using packaging tools

### ISSUE THREAD

**Issue by tlepoint** [fplll/fplll#190]
For information, fplll is now available on macOS via [homebrew](http://brew.sh) (third-party packaging tool) 

`brew install homebrew/science/fplll`

(see [fplll.rb on homebrew-science](https://github.com/Homebrew/homebrew-science/blob/master/fplll.rb))

I think the README.md file could be slightly reorganized. Indeed, the dependencies are only when building from GitHub (one does not need autotools when building from the release and when using fplll). It could be nice to have the dependencies for using the libraries and ways to install it from 3rd party tools (TODO: make ubuntu / debian / archlinux packages), and an explanation on how to build it from source with autotools as dependency.

**Comment by malb** [comment]
Good idea! Btw https://ftp-master.debian.org/new/fplll_5.0.1-1.html Feel free to send a PR, otherwise, I'll try to get around to it soon.

**Comment by malb** [comment]
We might want to throw in links like https://buildd.debian.org/status/package.php?p=fplll&suite=experimental#problem-0 to tell users how the package is doing on various platforms.

**Comment by lducas** [comment]
Closed ?

**Comment by malb** [comment]
This still seems open to me.
