### ISSUE TITLE
--march=native -O3 as default?

### ISSUE THREAD

**Issue by malb** [fplll/fplll#198]
Do we want `--march=native -O3` as default? It gives a tidy speed bump cf. #169

**Comment by shi-bai** [comment]
This is OK for me. But just mention that there are certain scenarios that this option may cause some problem. E.g. on a cluster with various cpus, the fplll compiled with  -march=native or -mtune may fail to work.

**Comment by malb** [comment]
Okay, let's not do it then but let's add something to the readme instead.

**Comment by shi-bai** [comment]
Good point to document it -- I added in https://github.com/fplll/fplll/pull/202

**Comment by lducas** [comment]
Stupid question, but where and when in the configure/compilation process can we add --march=native ?

**Comment by malb** [comment]
Run `CXXFLAGS="-O3 --march=native" ./configure && make clean && make`

**Comment by lducas** [comment]
Bummer...

```
> CXXFLAGS="--march=native -O3" ./configure && make clean && make

checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... no
checking whether g++ supports C++11 features with -std=c++0x... no
checking whether g++ supports C++11 features with +std=c++11... no
checking whether g++ supports C++11 features with -h std=c++11... no
configure: error: *** A compiler with support for C++11 language features is required.
```
