### ISSUE TITLE
Adding multi-threading for enumeration

### ISSUE THREAD

**Issue by cr-marcstevens** [fplll/fplll#206]
Multi-threading for enumeration has been discussed at the previous fplll days. 
My suggestion are the following:
- use C++11 threads, mutexes and atomic integers 
  (platform independent and no other library dependencies)
- write/import a thread-pool for auxiliary threads (so excluding the main thread). 
  It should include a lockfree queue for jobs (lockfree will give better performance for many cores).
  (e.g., we can import the single header lib https://github.com/vit-vit/CTPL or similar)
  By default nr of aux.threads will remain zero for single-threadness.
- optionally add fplll-consistent API wrapping around threadpool API:
  - to (re)set number of total threads (nr of auxiliary threads will be one less)
  - to add job to job-queue
  - to wait until all jobs have finished (during which main thread will also process jobs)
  
  The first function needs to be called to enable multi-threading, 
  the last two will be used internally in fplll for parallelizable work like enumeration.

Comments?

**Comment by cr-marcstevens** [comment]
I wrote a header-only thread_pool for other fplll-extenum, but may be of wider use for fplll also:

https://github.com/cr-marcstevens/snippets/blob/master/cxxheaderonly/thread_pool.hpp

**Comment by malb** [comment]
We can close this ticket once the multicore enum code of @cr-marcstevens is merged.

**Comment by cr-marcstevens** [comment]
Merged PR #376
