### ISSUE TITLE
Switch to libtool 2.4.6 (from 2.4.2)

### ISSUE THREAD

**Issue by fingolfin** [fplll/fplll#209]
The tarball for fplll 5.0.2 was prepared using libtool 2.4.2. Unfortunately, that version of libtool handles Mac OS X 10.10 and later incorrectly (it incorrectly treats them as 10.1.x instead).

Thus, it would be nice if the next released could be prepared with libtool 2.4.6.

Depending on how and where you create the tarballs, that may require installing a custom version of libtool, manually, but luckily that is relatively easy.

**Comment by malb** [comment]
We are using Travis CI to produce these, not sure how easy it would be to upgrade there.

**Comment by malb** [comment]
In the mean time I just manually uploaded a tarball with libtool 2.4.6. Can you check if this works.

**Comment by fingolfin** [comment]
For Travis, the easiest probably would be to use a backport .deb, but there doesn't seem to be one for libtool 2.46.

Instead, you can simply install it manually. I.e. wget the libtool 2.4.6 tarball, and run `.configure && sudo make` (you have enabled sudo in your `.travis.yml`, so that should work). Googling a bit shows that some people already do this, see https://fuchsia.googlesource.com/third_party/libpng/+/upstream/libpng17/.travis.yml  or https://github.com/solomonik/ctf/blob/master/travis/install-autotools.sh

**Comment by fingolfin** [comment]
Yes, your new tarball does the right thing in its configure (the glob pattern `10.[012]*` was replaced by `10.[012][,.]*`). Thanks!

**Comment by lducas** [comment]
Should this be closed ?

**Comment by malb** [comment]
I don't think this was resolved yet. Actually, perhaps the new tarball is broken again (?)
