### ISSUE TITLE
--without-qd broken

### ISSUE THREAD

**Issue by fingolfin** [fplll/fplll#210]
Using --without-qd is broken. As per the default behaviour of autoconf, it is equivalent to `--with-qd=no`, but the fplll configure.ac does not handle that suitably. This code in it is the culprit:
```
AC_ARG_WITH(qd,
   AS_HELP_STRING([--with-qd=@<:@=DIR@:>@], [quaddouble install directory]), [
      CPPFLAGS="$CPPFLAGS -I$withval/include"
       LDFLAGS="$LDFLAGS -L$withval/lib"
       qd_lib_path="$withval/lib"
   ])
```

It leads to `-Lno/lib` being added to LDFLAGS, leading to a make error .

**Comment by malb** [comment]
Hi, can you check if this fixes the issue? Thanks for reporting!

**Comment by fingolfin** [comment]
Yes, it passes my sophisticated check: `./autogen.sh && ./configure --without-qd && make -j4` :-)
