### ISSUE TITLE
New API: please provide migration hints ?

### ISSUE THREAD

**Issue by jgmbenoit** [fplll/fplll#214]
At the end of the latest list of changes in NEWS (Changes in fplll-5.0), we read ``FP API improved to allow for more readable/natural code''. Fine. Is there somewhere any hint to migrate from fplll4 to fplll5 API ? If not, a few words about it may help.
Thanks in advance.

**Comment by malb** [comment]
What we mean by this is that you can write `c = a+ d*sqrt(b*b) + 2.00` now, without performance loss. No more `c.add(c,a)`.
