### ISSUE TITLE
Return value for enum (with and without multi solutions)

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#222]
Appart from the vector itself, enumeration returms another real number, that I would expect to be the length of the solution but doesn't seem to be. 

For example, in the `test_multisol_enum.py` file in branch develop, all the found vectors have length 48, but the extra return value is 48.5 for the main solution (which is the input radius) and 0.75 for all the other ones...

What is really the desired behaviour of this return value ?

**Comment by lducas** [comment]
AH ! 
Got it. the .75 is 48/64 (where 48 is the length of the solution), so it is most likely a exponent renormalization issue, as pointed out in a previous email.

The 48.5 of the main solution is the leftover bound for the enumeration, Previously, this was OK since this bound was always set to the best solution so far, but this was messed up by the multisol feature.


Martin and I will do this repair, assuming the desired behaviour is the length of the solution, and not the leftover bound for the enumeration.
@cr-marcstevens @gbonnoron, please yell if I understood something wrong.

**Comment by lducas** [comment]
PS1: this is not respect to master but to develop>
PS2: after looking at evaluator.cpp, I'm unsure I feel confident enough to edit a single line of that file...

**Comment by lducas** [comment]
A partial solution was pushed in branch develop:

1. It is only implemented for the virtual <FT>FastEvaluator. 
(As I am unsure this is a solution everyone is happy with yet, I did not wanted to duplicate this to the many places it would be required.)
2. The norm of auxiliary solution is properly renormalized
3. The main solution now *is* the shortest one
4. The main outputted distance *is not* the length of the shortest vector, but the leftover enumeration bound
(they used to always be equal before this change, and shall still be the case when not using auxiliary solutions)
5. The main solution is also included in auxiliary solution list: so we do have its actual norm despite 4.

Yell at me if this makes you unhappy.

**Comment by malb** [comment]
I think this is resolved now, closing. Feel free to reopen.
