### ISSUE TITLE
MatGSOGram class

### ISSUE THREAD

**Issue by kodebro** [fplll/fplll#223]
One also would like to apply fplll when a lattice is given in the form of a Gram matrix (instead of in the form of a basis).

Making a new class MatGGSO (which has no basis, but only a Gram matrix), derived from MatGSO, I discovered that lll.cpp (and maybe other files) makes explicit calls to the variable b of the MatGSO object.
It might be a good idea to make all variables in MatGSO that are explicitly linked to the basis (b, init_row_size, etc.) private.

Also, I think MatGSO should be a derived class from MatGGSO, instead of the other way around. For me this makes more sense logically.

**Comment by kodebro** [comment]
Trying to make `b` private in fplll/gso.h, I found that the following files make explicit calls to `b`: fplll/lll.cpp and fplll/bkz.cpp.
In lll.cpp the calls are of the form `m.b.get_max_exp()` and `m.b[0].is_zero()`. I resolved this by making functions `get_max_exp_of_b()` and `b_row_is_zero(0)` inside fplll/gso.h.

The situation with bkz.cpp is more difficult. The easy-to-resolve calls are of the form `m.b[num_rows - 1].is_zero()` and `m.b.get_cols()`, which I resolved by `b_row_is_zero(num_rows - 1)` and a new function in fplll/gso.h `get_cols_b()`. 

The hard-to-resolve part in bkz.cpp is the function `dsvp_postprocessing`, which uses direct row operations on `b` in the form of negating a row, swapping rows and substracting a row from another row. The first (but probably not right) solution that came to my mind was to resolve this by replacing these row-operations by 'indirect' row-operations applied by MatGSO.

After changing all this, the _make test_  gives 1 FAIL for test_svp. Although test_svp does give the right answer, it gives the following error:
_Last dual vector too long by more than 1.11022e-16
FAIL test_svp (exit status: 255)_

So, a few questions arise here:
(1) In `dsvp_postprocessing`, what are the objections against using MatGSO row operations? If not, how does one resolve this to make it also applicable for the future derived class `MatGGSO` (Gram matrix version)?
(2) How to make the following functions virtual, for the future derived class `MatGGSO` (with only a Gram matrix)?  `b_row_is_zero(int i)`, `get_max_exp_of_b()`. Or, how to append lll.cpp and bkz.cpp such that the Gram matrix version will fix?

**Comment by malb** [comment]
I'm all in favour of making our standard algorithms use the appropriate (wrapper) methods, but do we need to make `b` private? It would mean we now have to carry around two objects when we also want to reach for `b` at some point.

**Comment by kodebro** [comment]
In a lattice given by a Gram matrix, there is in fact only a 'symbolic' basis (not realized as Z-vector). So if one wants to reach `b` then, it doesn't exist.
So, if we do want to make a MatGGSO-class (Gram version derived from MatGSO) and if we do want to compute with this class, then I think that `b` should never be explicitly called. I can imagine that more sophisticated optimalizations of LLL do use `b` explicitly - those might not be suitable for lattices given by a Gram matrix.

**Comment by malb** [comment]
To me this suggest that the proposed inheritance hierarchy - inherit from `MatGSO` - is not such a great idea. Perhaps `MatGSO` and `MatGGSO` should both inherit from the same base class which defines an interface used by LLL and friends (where possible)?

**Comment by kodebro** [comment]
A mistake from my side caused the error with SVP. It should be resolved now. I am starting currently with a base class defining an interface.

**Comment by lducas** [comment]
Shouldn't we close this one ?
