### ISSUE TITLE
Documentation of the fplll tool

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#239]
Hi,

while updating the manpage I wrote for the fplll tools, I noticed a few things:
- a missing newline makes the -y switch doc follow the -s one ;
- the options for the -a switch and their docs don't have the same order (and it isn't the alphabetical one either)
- the -a switch says one of the options is sdbkz and the doc says it's sdb... the code says it's really sdb!

**Comment by malb** [comment]
Fixed
