### ISSUE TITLE
usability of `infinite loop in babai`

### ISSUE THREAD

**Issue by malb** [fplll/fplll#244]
The error message `infinite loop in babai` causes confusion amongst users, cf. https://github.com/fplll/fplll/issues/170#issuecomment-297404695 I propose:

1. We create an FAQ where we explain what that error message means and propose to increase precision (a second item could then explain how to do that depending on situation)

2. Add a link to the FAQ entry to the error message.

**Comment by joerowell** [comment]
I think we can symbolically close this issue (since #453 )
