### ISSUE TITLE
Tests on 32-bit

### ISSUE THREAD

**Issue by malb** [fplll/fplll#245]
Sage [reports](https://trac.sagemath.org/ticket/23057#comment:1) that fplll doesn't pass self tests on 32-bit systems. In particular, `test_pruner` is failing.

**Comment by lducas** [comment]
I will make the comparison a bit looser. But I'm not sure how to test things in a 32bit env. I don't have one, maybe I can set a virtual machine or something ?

**Comment by malb** [comment]
Fixed.
