### ISSUE TITLE
GaussSieve API

### ISSUE THREAD

**Issue by malb** [fplll/fplll#248]
Hi, I have a couple of issues with the API of `GaussSieve`

- I think `GaussSieve` should use flags not `verbose = True` to be consistent with the rest of `fplll`
- ~~Why do we have public methods to `run_Xsieve()` when the user has to specify `alg=X` at object creation? Isn't that invitation to the user to shoot themselves in the foot? I'd suggest to have only one public `sieve()` method~~
- ~~Why do we have a separate public call to set the target norm (I propose to rename `goal_norm` to `target_norm`), shouldn't that be a parameter for the `sieve()` method?~~
- It would be good to have a public function to recover more than one vector from the sieve, say an iterator?

**Comment by shi-bai** [comment]
Thanks Martin. What does the first one mean? "I think GaussSieve should use flags not verbose = True to be consistent with the rest of fplll"

**Comment by malb** [comment]
LLL, BKZ etc. accept a `flags` parameter, one of which is `LLL_VERBOSE` or `BKZ_VERBOSE`. I suggest to use the same API for sieving, i.e. to turn the `verbose` parameter into `flags` and to define `SIEVE_VERBOSE`
