### ISSUE TITLE
GaussSieve does not necessarily return shortest vector

### ISSUE THREAD

**Issue by malb** [fplll/fplll#249]
Using fpylll's [sieve branch](https://github.com/fplll/fpylll/tree/sieve) and calling

```python
from fpylll import *
A = IntegerMatrix.random(40, "qary", k=20, q=127); A = LLL.reduction(A)
w = SVP.shortest_vector(A)
v = GaussSieve(A, algorithm=2)()
sum([w_**2 for w_ in w]) == sum([v_**2 for v_ in v])
```

I'm occasionally getting `False`. Is that to be expected?

**Comment by shi-bai** [comment]
I think it is not guaranteed that sieving outputs the shortest vector (which depends on the termination condition). I do not know what is a good termination condition: there is some balance between time and quality involved.

**Comment by malb** [comment]
Kay, closing this issue then.
