### ISSUE TITLE
test_lll_gram on rpi2

### ISSUE THREAD

**Issue by lgremy** [fplll/fplll#262]
I compiled fplll, with gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1), and obtained the following fail by running ```make check``` on my Raspberry Pi 2, with an ARMv7 Processor rev 5 (v7l) processor.
```
=======================================
   fplll 5.1.0: tests/test-suite.log
=======================================

# TOTAL: 9
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_lll_gram
===================

The gram GSO-object is not LLL-reduced after calling LLL
FAIL test_lll_gram (exit status: 255)
```

**Comment by malb** [comment]
Can you run `./test_lll_gram` to see where it bombs out and how?

**Comment by kodebro** [comment]
I had a quick talk with Laurent and Léo, and apparently the following lines are the troublemakers:
`status |= test_int_rel<mpz_t, double>(200, 100);`
` status |= test_int_rel<mpz_t, mpfr_t>(200, 100);`
It seems that the dimension (first argument) is way to high for the precision. As Léo pointed out to me, those dimensions are carefully chosen, depending on the precision. 

In my local repository, I deleted all `test_int_rel` with dimension 200. I think deleting those tests should do the trick.

I don't know (yet) an explanation why the test does work for MatGSO-objects but doesn't for MatGramGSO-objects.

**Comment by lgremy** [comment]
In the attached file, I list matrices that failed, and a one that does not failed, because the matrices are randomly generated and I prefer to explicitly give them.
[test_lll_gram.txt](https://github.com/fplll/fplll/files/1135909/test_lll_gram.txt)

**Comment by kodebro** [comment]
I investigated somewhat more, and found the bug. The main problem is that the full Gram matrix was not copied. I will fix this - the good news is that the error is (probably) not in the code of GramGSO.

**Comment by kodebro** [comment]
I will very soon make a pull-request for this!

**Comment by gilvillard** [comment]
Numerically, for a given precision, high dimensions may not be achievable. Typically d > 170 (180) with doubles in the general case if Cholesky is used. However, this limit threshold also depends on the input bit size and if the later is small the threshold may be higher. If we look at a sort of condition number cond(R) for R (of QR), given by the Frobenius norm of |R| |R^(-1)|, the threshold with doubles correspond to log2 cond(R) \approx 25 for the output basis. 

For intrel and 100 input bits, the output typically has log2 cond(R) \approx 13. The reduction should "always" succeed with doubles.  If one tries with 800 input bits things may also succeed with doubles and log2 cond(R) \approx 24. 

Intrel with 1000 input  will typically lead to an output log2 cond(R) \approx 27. The wrapper will in general switch to long doubles at index say 180.

**Comment by tobihan** [comment]
Any progress on this? We have the same test failing in Debian using fplll 5.2.0 on armel, armhf, mips, hppa and powerpc, see
https://buildd.debian.org/status/package.php?p=fplll&suite=experimental

**Comment by malb** [comment]
No progress, sorry. Part of the trouble is that we don't have access to any of these systems for testing/bugfixing. Is QEMU the preferred choice for this kind of thing?

**Comment by tobihan** [comment]
Probably, I never used QEMU.

Do you recommend to temporarily work around this in Debian by disabling the tests with dimension 200?

@kodebro didn't you find the bug?

**Comment by kodebro** [comment]
I am so sorry! I totally forgot this issue -- I will take a good look at it this weekend! Thank you for reminding me...!
Hopefully creating a PR before Sunday... if it not happens, please give me a slap.

**Comment by tobihan** [comment]
Hey @kodebro any news?

**Comment by kodebro** [comment]
Ai! I am sorry guys for these postponing messages, I am really busy right now. I hope I'll getting stuff done near the end of the week...

**Comment by kodebro** [comment]
@gilvillard I really like your analysis; but is it (maybe) possible that this analysis only works in the case where we use the basis-representation of the lattice? If we make a gram matrix `G` out of an intrel matrix `B` with bit size 100 and dimension 200 (i.e. `G = B*B^T`) could it be that by this squaring make things worse?

Overall, I am going to delete the lines `status |= test_int_rel<mpz_t, double>(200, 100);` and `status |= test_int_rel<mpz_t, mpfr_t>(200, 100);`.

**Comment by kodebro** [comment]
In the folllowing PR [https://github.com/fplll/fplll/pull/342](url), I removed the lines and cleaned up and improved the test code.
I found that during Babai size-reduction in LLL, the big numbers cause overflow when converted to (long) double.

```
template <class ZT, class FT>
void MatGSOGram<ZT, FT>::row_addmul_we(int i, int j, const FT &x, long expo_add)
{
  FPLLL_DEBUG_CHECK(j >= 0 && i < n_known_rows && j < n_source_rows);
  long expo;
  long lx = x.get_si_exp_we(expo, expo_add);

  if (expo == 0)
  {
    if (lx == 1)
      row_add(i, j);
    else if (lx == -1)
      row_sub(i, j);
    else if (lx != 0)
      row_addmul_si(i, j, lx);
  }
```

In   `long lx = x.get_si_exp_we(expo, expo_add);`, the conversion goes wrong.

In 'everyday' LLL-reductions this is not a problem, I think, because Wrapper is used.

**Comment by lgremy** [comment]
```
============================================================================
Testsuite summary for fplll 5.2.0
============================================================================
# TOTAL: 9
# PASS:  9
```

Think it is time to close the issue.
