### ISSUE TITLE
Modules should go through GSOInterface rather than GSO

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#274]
Certain decision are made by looking directly at the basis rather than through the GSO. It seems to be related to size of entries to decide numerical precision ? 

- Determine what functionality are exactly needed by other modules
- Find how to provide using only a Gram matrix
- Provide the functionnality on both GSO and GSO_gram through GSO_interface

**Comment by WvanWoerden** [comment]
Being worked on in this [pull request](https://github.com/fplll/fplll/pull/378). LLL, BKZ and Enum objects all accept MatGSOInterface objects.
