### ISSUE TITLE
Exception handling in bkz.h

### ISSUE THREAD

**Issue by lducas** [fplll/fplll#284]
Many function are duplicated, for a feature that is not clearly needed. Remove it and see what happens, especially in fpylll.

**Comment by lducas** [comment]
Shi, can you comment on your conclusion ?

**Comment by malb** [comment]
It's fixed in https://github.com/fplll/fplll/commit/b42524a6e62a03a6d818d03740232afb08b9920d

**Comment by shi-bai** [comment]
Hi Leo,

It's linked to the pull request https://github.com/fplll/fplll/commit/
b42524a6e62a03a6d818d03740232afb08b9920d
The  *_ex functions are not used elsewhere. I merged the request which
closed the ticket.

Are you referring to other duplicated functions? Feel free to reopen it.

Cheers,
Shi

**Comment by lducas** [comment]
Hi Shi, I'm just embarrassing myself. Sorry, and thanks.

**Comment by shi-bai** [comment]
Thanks Leo. There are indeed functions in gso* and util.cpp which are
unused/duplicated. I guess it's fine to leave those in gso* for future use.
I will try to clean util.cpp a bit.
