### ISSUE TITLE
-Warray-bound on gcc 6.4.0

### ISSUE THREAD

**Issue by shi-bai** [fplll/fplll#300]
> [from Paul Zimmermann]
> 
> compile fplll (git version) with gcc 6.4.0 I get a warning:
> 
>   CXX      gso.lo
> In file included from bkz_param.h:23:0,
>                  from bkz.h:21,
>                  from bkz.cpp:20:
> bkz.cpp: In function ‘int fplll::bkz_reduction(fplll::IntMatrix*, fplll::IntMatrix*, const fplll::BKZParam&, fplll::FloatType, int)’:
> bkz.cpp:875:92: warning: array subscript is outside array bounds [-Warray-bound]
>      FPLLL_ABORT("Compiled without support for BKZ reduction with " << FLOAT_TYPE_STR[sel_ft]);
>                                                                        ~~~~~~~~~~~~~~~~~~~~~^
> defs.h:73:26: note: in definition of macro ‘FPLLL_ABORT’
>      cerr << "fplll: " << x << endl;                                                                \
>                           ^
> 

This warn does not appear on gcc 4.9.2. It seems that gcc 6.4.0 has a stricter check when -Wall (and -Warray-bounds is enabled). 

enum FloatType
{
  FT_DEFAULT,
  FT_DOUBLE,
  FT_LONG_DOUBLE,
  FT_DPE,
  FT_DD,
  FT_QD,
  FT_MPFR
};

const char *const FLOAT_TYPE_STR[7] = {"", "double", "long double", "dpe", "dd", "qd", "mpfr"};

bkz.cpp:875:92: has
 
  else
  {
    FPLLL_ABORT("Compiled without support for BKZ reduction with " << FLOAT_TYPE_STR[sel_ft]);
  }

I don't know what causes the warning. Perhaps the enum should not be used as integers?

**Comment by vinc17fr** [comment]
I don't have any issue with GCC 6.4.0 and GCC 7.1.0 on the following code:
```
enum FloatType
{
FT_DEFAULT,
FT_DOUBLE,
FT_LONG_DOUBLE,
FT_DPE,
FT_DD,
FT_QD,
FT_MPFR
};

const char *const FLOAT_TYPE_STR[7] = {"", "double", "long double", "dpe", "dd", "qd", "mpfr"};

void g (const char *);

void f (enum FloatType sel_ft)
{
  g (FLOAT_TYPE_STR[sel_ft]);
}
```

So, the context seems to matter.

**Comment by shi-bai** [comment]
tested by Paul on gcc 4.9.2 again the current git. no warnings.
