### ISSUE TITLE
subsolutions

### ISSUE THREAD

**Issue by malb** [fplll/fplll#307]
It seems `subsoldists` is somehow zero-ed during enumeration. That is, in line

  https://github.com/fplll/fplll/blob/master/fplll/enum/enumerate_base.h#L113

I get a floating point value > 0 for e.g. subsoldists[1] but in

  https://github.com/fplll/fplll/blob/master/fplll/enum/enumerate_base.cpp#L28

I get a zero. This seems to prevent sub-solutions from working.

**Comment by malb** [comment]
CCing @cr-marcstevens so that he sees that I tracked it down my bug somewhat further.

**Comment by cr-marcstevens** [comment]
I see a small bug that is not present in my fplll-extenum:
`if (findsubsols && newdist < subsoldists[kk])`
must be
`if (findsubsols && newdist < subsoldists[kk] && newdist != 0.0)`
to prevent the trivial zerovector to be seen as an improvement. 

This needs to be fixed at line 36 & 212 (can't do from my smartphone at the moment) .

**Comment by malb** [comment]
You are legend, that fixes it. I'll PR.

**Comment by lducas** [comment]
It would be even more awesome if it doesn't consider the current vector at that position as a subsolution, (ie the vectors of the form [+/-1, 0, 0, ... ]. The idea is that it would allow rerandomizing to the next best vector even if nothing strictly better is found.

**Comment by malb** [comment]
You mean to even store longer solutions?

**Comment by lducas** [comment]
Yes, but maybe lets make that a feature request, I can already check the PR. Thx !

**Comment by cr-marcstevens** [comment]
Currently `subsoldists[k]`  defaults to ||b_k^*||,  so b_k cannot be an output, only vectors that are shorter. 
But we could generalize the mechanism similar to solutions, allowing a custom bound and have the evaluator store up to N vectors with any of the strategies. 
The evaluator could also filter out any trivial vectors of the form `[+/-1 0.. 0]`. 
Most of that work would be in evaluators with a tweak to the enumerator API.
