### ISSUE TITLE
tarball for 5.1.1 is named fplll-5.1.0.tar.gz

### ISSUE THREAD

**Issue by ilovezfs** [fplll/fplll#315]
It looks like on https://github.com/fplll/fplll/releases that the download
https://github.com/fplll/fplll/releases/download/5.1.1/fplll-5.1.0.tar.gz
should be
https://github.com/fplll/fplll/releases/download/5.1.1/fplll-5.1.1.tar.gz

**Comment by malb** [comment]
thanks for spotting this, I've deleted the release. I shouldn't have attempted a shotgun release. Looks like we'll publish 5.2 soon, hopefully a with correct version number …

**Comment by ilovezfs** [comment]
>thanks for spotting this

No problem!
