### ISSUE TITLE
Gram GSO LLL doesn't work with gram matrices with big coefficients (was: doesn't work with non-representable)

### ISSUE THREAD

**Issue by kodebro** [fplll/fplll#328]
It seems that GramGSO LLL doesn't work on gram matrices that are *not* of the form G = B*B^T. I tried to put in the following matrix:
`[[3559941422478111945438014 2000384006369912794808478 2229599748450132568394343 749522257835011031240761]
[2000384006369912794808478 1124045510320513281506436 1252845243251596873063781 421167698862786742516112][2229599748450132568394343 1252845243251596873063781 1396403605660581339138906 469427566132091561402657][749522257835011031240761  421167698862786742516112  469427566132091561402657 157806982846091154484154]]`

Reduction of fplll:
`[ 154    0     0                                               0 ]
[  37 3816     0                                               0 ]
[  17 1711  9146                                               0 ]
[ -60 1614 -3036 -3672475935620874863122493963413516150045490214 ]`
Real reduction:
`[ 4 -1 -1  1]
[-1  4 -1  1]
[-1 -1  4  1]
[ 1  1  1  4]` 

Something is wrong here. I will make a branch in my cloned repository with a mutated testfile including this example soon.

**Comment by malb** [comment]
FWIW Here's the same example reproduced in fpylll

```python
In [9]: A = IntegerMatrix.from_matrix([[3559941422478111945438014, 2000384006369912794808478, 2229599748450132568394343, 749522257835011031240761], [2000384006369912794808478, 1124045510320513281506436, 1252845243251596873063781, 421167698862786742516112], [2229599748450132568394343, 1252845243251596873063781, 1396403605660581339138906, 469427566132091561402657], [749522257835011031240761, 421167698862786742516112, 469427566132091561402657, 157806982846091154484154]])

In [11]: M = GSO.Mat(A, gram=True)
In [12]: LLL.Reduction(M)()
In [13]: print A
[                 58858964 2000384006369912794808478                  2229599748450132568394343 749522257835011031240761 ]
[                 11273758                2394353606                  1252845243251596873063781 421167698862786742516112 ]
[                 -7765351                -350937627 -84743144112504095273476788176669742654916 469427566132091561402657 ]
[ 749522257835011031240761  421167698862786742516112                   469427566132091561402657 157806982846091154484154 ]

```

**Comment by kodebro** [comment]
Shouldn't there be an `update_gso()` somewhere inbetween?
When I tried this, I got
```
sage: M = GSO.Mat(A, gram = True)
sage: print M.G
[ 3559941422478111945438014 2000384006369912794808478 2229599748450132568394343 749522257835011031240761 ]
[ 2000384006369912794808478 1124045510320513281506436 1252845243251596873063781 421167698862786742516112 ]
[ 2229599748450132568394343 1252845243251596873063781 1396403605660581339138906 469427566132091561402657 ]
[  749522257835011031240761  421167698862786742516112  469427566132091561402657 157806982846091154484154 ]
sage: M.update_gso()
False
```

**Comment by kodebro** [comment]
I still use the matrix `A = [[4,1,1,1],[1,4,1,1],[1,1,4,1],[1,1,1,4]]`. I choose a different Gram matrix by computing `B = DT * A * D`, for some unimodular `D`. If the resulting Gram matrix is too big, the GSO cannot be updated. See the following two examples.
```
sage: MB1 = GSO.Mat(B1, gram=True)
sage: D = IntegerMatrix.from_matrix([[1,0,0,0],[20,1,0,0],[30,20,1,0],[40,30,2,1]])
sage: DT = (IntegerMatrix.from_matrix([[1,0,0,0],[20,1,0,0],[30,20,1,0],[40,30,2,1]])).transpose()
sage: A = IntegerMatrix.from_matrix([[4,1,1,1],[1,4,1,1],[1,1,4,1],[1,1,1,4]])
sage: B1 = DT*A*D
sage: MB1 = GSO.Mat(B1, gram=True)
sage: MB1.update_gso()
True
sage: LLL.Reduction(MB1)()
sage: print MB1.G
[  4 603   211 393 ]
[  1   4 10101   9 ]
[ -1  -1     4 141 ]
[ -1  -1     1   4 ]
```
The lower part of the last printed matrix [which is the relevant part] clearly gives the good answer. Now we consider the following loop
```
for i in range(10):
....:     D = (IntegerMatrix.from_matrix([[1,0,0,0],[2*10**i,1,0,0],[3*10**i,2*10**i,1,0],[4*10**i,3*10**i,2*10**i,1]]))
....:     DT = (IntegerMatrix.from_matrix([[1,0,0,0],[2*10**i,1,0,0],[3*10**i,2*10**i,1,0],[4*10**i,3*10**i,2*10**i ,1]])).transpose()
....:     G = D*A*DT
....:     MG = GSO.Mat(G, gram=True)
....:     print MG.update_gso()
....:     
True
True
True
True
True
True
True
True
False
False
```
So from `i = 8` the entries are too big to do the `gso_update()` function. Putting `LLL.Reduction(M)()` and `print M.G` in above loop confirms that LLL then is not able to do his job.

**Comment by malb** [comment]
I presume this has nothing to do with Python-wired or not, right? Also, shouldn't LLL succeed even when GSO does not as it improves the basis as it computes the GSO and thus improves numerical stability as it goes along and computes more of the GSO?

**Comment by kodebro** [comment]
I think this indeed has nothing to do with the Python wiring.
I don't know precisely about whether LLL should succeed if GSO doesn't.

**Comment by shi-bai** [comment]
It seems to me, when the input lattice has large coefficients, then directly use update_gso() could break. But using size_reduction() or lll_reduction() usually works as Martin noted above.

**Comment by kodebro** [comment]
@shi-bai There is still the main question why LLL just doesn't work on these slightly bigger Gram-matrices. Also issue #343 seems related; is this 'overflow behaviour' intended?

**Comment by kodebro** [comment]
I think this problem is resolved by the following pull request: [#349](https://github.com/fplll/fplll/pull/349).

**Comment by malb** [comment]
I'm now seeing:

```python
[  4 2229599748450132568394343 2000384006369912794808478  469427566132091561402657 ]
[  1                         4  421167698862786742516112  749522257835011031240761 ]
[ -1                         1                         4 1252845243251596873063781 ]
[ -1                         1                        -1                         4 ]
```

for the example above.

**Comment by kodebro** [comment]
That's precisely what it should be. The upper-triangular part of the matrix is garbage [the operations on the Gram matrix are only done on the lower triangular].
The upper coefficients are artefacts [though I am still a bit concerned -> it seems that *some* operations are still performed on this upper-triangular part, otherwise the upper-triangular part should stay the same [w.r.t. the input Gram matrix], which is not].

**Comment by malb** [comment]
I'd guess that's an artefact of column loops running across the whole column as opposed to starting at the row index.

Also, do we want to update the upper triangular part after the computation perhaps?

**Comment by kodebro** [comment]
That looks nicer, right?
I am still a little bit troubled... is above matrix really a bi-unimodular transform of `[[4,1,1,1],[1,4,1,1],[1,1,4,1],[1,1,1,4]]`?

**Comment by malb** [comment]
Doesn't look like it:
```python
sage: A = matrix(ZZ, 4,4, [[  4, 2229599748450132568394343, 2000384006369912794808478,  469427566132091561402657 ],
[  1,                         4,  421167698862786742516112,  749522257835011031240761 ],
[ -1,                         1,                         4, 1252845243251596873063781 ],
[ -1,                         1,                        -1,                         4 ]])
sage: B = matrix(ZZ, 4,4, [[4,1,1,1],[1,4,1,1],[1,1,4,1],[1,1,1,4]])
sage: B.solve_left(A)
[-4699411320952136924605454/21   3635928972732930351384973/7   3101092241212417546351288/7 -1413418358027495994786883/21]
[-1170689956697797773756871/21 -1170689956697797773756850/21    592494645113903141285302/7  4075965848147279444928449/21]
[-1252845243251596873063792/21 -1252845243251596873063778/21 -1252845243251596873063757/21  7517071459509581238382682/21]
[                       -10/21                          4/21                        -10/21                         25/21]

```

For starters, this should be an integer matrix, right?

**Comment by kodebro** [comment]
Oh, but we shouldn't consider the upper-triangular row. 

fplll outputs:
``[  4 2229599748450132568394343 2000384006369912794808478  469427566132091561402657 ]
[  1                         4  421167698862786742516112  749522257835011031240761 ]
[ -1                         1                         4 1252845243251596873063781 ]
[ -1                         1                        -1                         4 ]
``

by which is meant:
``G = 
[  4 1  -1 -1 ]
[  1  4  1 1 ]
[ -1 1  4 -1 ]
[ -1 1  -1 4 ]``
This is because Gram-matrices are symmetric; so we do only computations on the lower triangle.

To see that the output of fplll is equivalent to the output ``H = [ 4 -1 -1 1] [-1 4 -1 1] [-1 -1 4 1] [ 1 1 1 4]`` of the very first comment of this issue, we set ``U = diag(1,-1,1,-1)`` and we apply ``UGU = H``

**Comment by malb** [comment]
Sure, I just figured the output should still be the result of elementary row operations, hence the test.

**Comment by kodebro** [comment]
Btw, to give an answer to your question: No, it shouldn't be an integer matrix anyway -- an elementary operation U on a Gram matrix goes on both sides:
H ->  UHU^T.

**Comment by malb** [comment]
Ouch!

**Comment by malb** [comment]
Right, so as far as I can tell, we can close this issue now, correct? Overwriting the upper triangular part should be a separate ticket

**Comment by kodebro** [comment]
> Right, so as far as I can tell, we can close this issue now, correc

Yes, let's do that.
> Overwriting the upper triangular part should be a separate ticket

Yes. Btw, I think I know why those elements occur in the upper triangular part. During `rotate_gram_left` in [the matrix.cpp code](https://github.com/fplll/fplll/blob/master/fplll/nr/matrix.cpp) the most efficient way to do the row-rotations is by changing pointers; this also affects the upper triangular part. But since it is just pointer-stuff no costly 'real arithmetic' is done in the upper-triangular part.
So indeed, only 'symmetrize' the matrix after reduction will do the job.
