### ISSUE TITLE
fplll 5.2.0 doesn't work on arm* and mips*

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#331]
The compilation of fplll 5.20 fails in Debian build bots for armel, armhf, mips and mipsel, because one of the tests fails during compilation: "The gram GSO-object is not LLL-reduced after calling LLL" (in test_lll_gram).

You can have a look at the build logs [here](https://buildd.debian.org/status/package.php?p=fplll&suite=experimental).

**Comment by lgremy** [comment]
This issue refers to Issue #262.

**Comment by SnarkBoojum** [comment]
Ah, indeed it's a duplicate : I hadn't seen. Closing, then.
