### ISSUE TITLE
Status of the file dpe.h.patch

### ISSUE THREAD

**Issue by lgremy** [fplll/fplll#334]
The file `dpe.h.patch` (at the root of the `fplll` directory) seems to be not used during the building of `dpe`, and then during the building of `fplll`. Should we move this patch as a comment of `fplll/nr/dpe.h` (in order to keep track of the modifications made on `dpe.h`)?

**Comment by shi-bai** [comment]
Thanks for spotting that. Is it only used for Solaris? I don't see the file is needed anywhere.
