### ISSUE TITLE
Contributing to fplll in Windows

### ISSUE THREAD

**Issue by tmmlaarhoven** [fplll/fplll#336]
Although most users and contributors to fplll probably use Linux, some others (like me) almost exclusively use Windows, in which case getting fplll running is not so easy. Would it be possible to make fplll usable in Windows as well, either by reducing the need for various tools/dependencies or by making a step-by-step guide how to install all these libraries?

While there are reasons to believe that everyone should switch to Linux, some software is only available for Windows, and most other C/C++ libraries I've used before (such as NTL) support Windows as well. Right now the only reason for me to have Linux installed on my machine at all is to contribute to fplll, since I can also use fplll through the Sage interface, and I can do my own C++ coding projects (without fplll) in Windows. Windows users may be more inclined to contribute to the code base if at least installing it would be simpler.

As for trying to install it in Windows: I tried a while ago, but eventually got stuck with the required libraries. (Unfortunately in Windows it's not a matter of `sudo apt-get install mpfr` to get them running...)

**Comment by cr-marcstevens** [comment]
If you are running Windows 10 and install its Bash for Windows subsystem then you can actually do `sudo apt-get install mpfr` etc.
You can easily install and run fplll in this subsystem, it's what I do.
(BTW it is not a VM, it actually uses the windows kernel instead of running its own linux kernel in a VM).

**Comment by tmmlaarhoven** [comment]
Cool, I wasn't aware of that feature. I can also get fplll running on Windows now, so I don't need a VM anymore - thanks! (Maybe it's something worth adding to the wiki?)

**Comment by malb** [comment]
+1, maybe you can give it a shot, note pitfalls and add a paragraph to the README?

**Comment by tmmlaarhoven** [comment]
At some point I must have messed something up when accessing the bash "root" directory through the Windows Explorer, as I got an error which apparently cannot be resolved much easier than by reinstalling everything. At least that gave me the chance to follow the same steps again and this time document the steps I took...

I've submitted an updated wiki with a paragraph for installing fplll this way in Windows 10.

**Comment by cr-marcstevens** [comment]
BTW It is absolutely not recommended to access the bash filesystem via Windows Explorer as this can corrupt those files.
Instead you can work the other way round by accessing your Windows drives as `/mnt/c` in bash.

**Comment by tmmlaarhoven** [comment]
Yes, unfortunately I found out the hard way...
