### ISSUE TITLE
randomness is machine dependent

### ISSUE THREAD

**Issue by malb** [fplll/fplll#340]
In commit db534dcb70c0ed5f5b9bd018f69f60dae78cebd5 we introduced the following code:

```C++
  if (bits > 32){ 
    unsigned long int tmp = mpz_get_ui(data);  
    gmp_randseed_ui(RandGen::gmpState, tmp*tmp);
  }
```

with commit message "Attempt to break the eventual linearity of the GMP PRNG." A side-effect of this code is that random matrices now depend on whether the architecture is 32-bit or 64-bit (because we're going via a long).

1. Do we really need this workaround? What goes wrong if we remove it?

2. If we need it, can we do `tmp & ~(1<<31)` or so to unify the two families?

**Comment by dstehle** [comment]
The reason for that tweak is that gnump's pseudo-random numbers are derived from a linear congruential generator. This could be bad for testing the behaviour of lattice reduction algorithms, as these algorithms are typically those that are used to break such pseudo-random number generators. 
It's not a cryptographically clean patch, but at least, by squaring tmp, every time we call 'rand' to get an integer, linearity with the previous call is broken. 

I don't know why "if (bits > 32)" is here. This potential linear dependancy occurs also when we ask for small random integers, not just long ones. I would remove this restriction.  

Why "unsigned long int"? It's just the type that  gmp_randseed_ui is waiting for. 
Your solution "tmp & ~(1<<31)" does the unifying job, I think. 
More precisely, adding a line tmp = tmp & ~(1<<31) just after the creation of tmp.

**Comment by malb** [comment]
using this strategy I'm now seeing:

```shell
 ./test_lll_gram 
The gram GSO-object is not LLL-reduced after calling LLL
The gram GSO-object is not LLL-reduced after calling LLL
```

CC: @kodebro

**Comment by kodebro** [comment]
This last issue should be solved by [https://github.com/fplll/fplll/pull/342](url).
