### ISSUE TITLE
Overflow (?) in row_addmul_we?

### ISSUE THREAD

**Issue by kodebro** [fplll/fplll#343]
I don't know whether this is a real issue or that I just don't understand the code, but replacing `row_addmul_we` in `gso.cpp` with the following code snippet gives many instances where the conversion from `x` to `lx` goes wrong.
```
template <class ZT, class FT>
void MatGSO<ZT, FT>::row_addmul_we(int i, int j, const FT &x, long expo_add)
{
  FPLLL_DEBUG_CHECK(j >= 0 && /* i > j &&*/ i < n_known_rows && j < n_source_rows);

  long expo;
  long lx = x.get_si_exp_we(expo, expo_add);
  if (x >= numeric_limits<long>::max()) { 
    cerr << "Error while B_" << i << " += " << x << "* B_" << j << ".\n";
    cerr << "lx= " << lx << ", x= " << x << " and expo_add= " << expo_add << endl;
  }
  if (expo == 0)
  {
    if (lx == 1)
      row_add(i, j);
    else if (lx == -1)
      row_sub(i, j);
    else if (lx != 0)
      row_addmul_si(i, j, lx);
  }
  else if (row_op_force_long)
  {
    row_addmul_si_2exp(i, j, lx, expo);
  }
  else
  {
    x.get_z_exp_we(ztmp2, expo, expo_add);
    row_addmul_2exp(i, j, ztmp2, expo);
  }
}
```
A part of `test_lll.log` [don't test other testfiles with this snippet] looks like
```
Error while B_2 += 1.80245e148* B_1.
lx= 6500785531101694976, x= 1.80245e148 and expo_add= 0
Error while B_2 += 3.53195e133* B_0.
lx= 7171102350607155200, x= 3.53195e133 and expo_add= 0
Error while B_2 += 2.39542e117* B_1.
lx= 8761380863150266368, x= 2.39542e117 and expo_add= 0
Error while B_2 += 4.31196e101* B_1.
lx= 7102740385413146624, x= 4.31196e101 and expo_add= 0
Error while B_2 += 2.05983e101* B_0.
lx= 6785989662551249920, x= 2.05983e101 and expo_add= 0
Error while B_2 += 1.33051e85* B_1.
lx= 7896216566755758080, x= 1.33051e85 and expo_add= 0
Error while B_2 += 5.60223e69* B_0.
lx= 7486724710431369216, x= 5.60223e69 and expo_add= 0
Error while B_2 += 1.26137e53* B_0.
lx= 6073269466316849152, x= 1.26137e53 and expo_add= 0
Error while B_2 += 3.67968e20* B_1.
```
Is this the intended behaviour?

**Comment by kodebro** [comment]
Quite possibly related to [https://github.com/fplll/fplll/issues/328](url) "GramGSO doesn't work with big coefficients"

**Comment by shi-bai** [comment]
Koen, do you have some example input lattice that triggers it? 

What does this line try to detect?
`  if (x >= numeric_limits<long>::max()) { 
`

If it is being called from babai(), it seems strange to see a big value for the x in 

`void MatGSO<ZT, FT>::row_addmul_we(int i, int j, const FT &x, long expo_add)
`
There the x is just mu_m_ant, which is generally small. Actually in the other ticket #305, we were trying to use that smallness.

**Comment by kodebro** [comment]
This line tries to detect whether x is too big to be converted into a long int.
In my branch [overflow](https://github.com/kodebro/fplll/tree/overflow), I added the mentioned code snippet. Apart from that, it is a pure copy of the master branch of fplll/fplll, [maybe the very latest changes are not included].
Compiling, going into the `test` folder, compiling `make test_lll` and run `./test_lll` gives a lot of overflows.
The test I isolated there is `status |= test_filename<mpz_t>(TESTDATADIR "/tests/lattices/example_in", LM_HEURISTIC);`, because this is a non-random matrix. The integer-relation generated matrices also give overflows.

**Comment by shi-bai** [comment]
Thanks I see the point. I don't know if this is a problem or not. I think such a large x can only happen for the first several around of the size reduction algorithm: 
Fig 1.5. Line 6. of http://perso.ens-lyon.fr/damien.stehle/downloads/LLL25.pdf

Here is my understanding: this might happen if (I guess after a swap in LLL) the two vectors are very unbalanced thus the coefficients "x" computed could be very large. But after the row got reduced by this perhaps-overflowed "x". It will re-compute this coefficients and eventually gets smoothed down to a tiny number and then to 1/2. But in the beginning, it is possible that this "x" is not accurate; and we only reduce using the last 64 bits of it (say). 

In the test_lll, eventually the lll will succeed.

**Comment by malb** [comment]
Should this be closed then?
