### ISSUE TITLE
Clean up upper tringular part of Gram Matrix after LLL

### ISSUE THREAD

**Issue by malb** [fplll/fplll#350]
The upper triangular part of the Gram Matrix after LLL is currently left filled with garbage. It would be nice for the user to clean this up before we release the object and does not cost much.

**Comment by lducas** [comment]
IIUC, the use don't get direct access to the underlying data of MatGSOInterface. Could we simply just return 0 when he requests r or mu on the upper triangular part, rather than changing the underlying algorithms ?

**Comment by malb** [comment]
I meant the case when the user inputs a Gram matrix. It might make sense to make this one pretty at the end. I agree with not touching `r` and `mu`

**Comment by lducas** [comment]
You meant *and* wrote Gram, and I read GSO. my apologies.

**Comment by kodebro** [comment]
There is already a function doing this in GramGSOInterface, `symmetrize_g()`. This will return an error if the pointer to the gram matrix is nullpointer; if we want to use this function we just should let do it nothing whenever the pointer is zero. 
The main question is *when* to apply this function.

**Comment by kodebro** [comment]
See [this pull request](https://github.com/fplll/fplll/pull/381/)

**Comment by malb** [comment]
Resolved by #381
