### ISSUE TITLE
Verbose in wrapper

### ISSUE THREAD

**Issue by lgremy** [fplll/fplll#355]
I ran the following computation `latticegen r 170 17000 | fplll -a lll -e 0.501 -v` and get
```
Discovering vector 141/170 cputime=308339
Discovering vector 142/170 cputime=314856               
End of LLL: failure: infinite loop in babai             
====== Wrapper: end of fast method ======                   
                                                       
====== Wrapper: calling fast<mpz_t,long double> method ======
[…]                                     
Discovering vector 2/170 cputime=0                         
Discovering vector 3/170 cputime=0      
```
Instead of `Discovering vector 2/170 cputime=0`, I was expecting to get a `cputime` larger than `314856`, in other word, having `cputime` that accumulate the time of the whole computation.

Do you think that the actual behavior is the expected one, or do you think that `cputime` should accumulate the complete timing (except for the proved part)?

**Comment by malb** [comment]
It matches my expectation since those cputimes are local to the computation being run. We could change it but it would require a bit of infrastructure to pass on already elapsed cputime to LLL algorithms. TBH I'm not sure it's worth it.

**Comment by lgremy** [comment]
Ok, thanks. It is true that the change would require to modify the infrastructure of the LLL object. I close it.
