### ISSUE TITLE
Bugfix release, but api incompatible and soname bump

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#357]
I'm a bit annoyed: 5.2.1 is supposed to be a bugfix release, but it comes with a soname bump, and big api changes (fplll/util.h's scalar_product and sqr_norm went away -- I saw that because it breaks fpylll).

From what I saw in Debian, only fpylll is broken by the change.

What can we do?

**Comment by malb** [comment]
Crap, sorry! It's an artefact of fplll being a research library, not developed with a view towards API stability, and me not really knowing what I do. AFAIK the SONAME bump is required (?) I clearly shouldn't have called it a bugfix release. is there anything we can do to make your life easier?

**Comment by SnarkBoojum** [comment]
Well, the soname bump might be correct since there was an api change (see the [rules](https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html#Updating-version-info)), but calling it a bugfix and just incrementing the minor version of the software was a big surprise. 

The good news is that as far as I can tell only fpylll was broken, but I can only check what is in Debian and I only tested the direct reverse depends, so you might still have users crying somewhere.

I didn't upload that new version to Debian since I saw the problem beforehand, so as long as we get a fixed fpylll we should do well on our side. I hope the other packagers (for other distributions) will see the problem in advance too...

**Comment by malb** [comment]
Makes sense. There is already a new FPyLLL release to go with this FPLLL release: https://github.com/fplll/fpylll/releases but see https://github.com/fplll/fpylll/issues/121#issuecomment-391532554 I think most packages relying on FPLLL will be fine, though, since they only use a few high level functions which are very stable.

**Comment by SnarkBoojum** [comment]
The fpylll packager will check if it's compatible with both versions of fplll, which will ease things.

**Comment by malb** [comment]
I think this one can be closed, we shall do better in the future.
