### ISSUE TITLE
BKZ-abortion working correctly?

### ISSUE THREAD

**Issue by MiBu84** [fplll/fplll#363]
I'm playing around with the abortion of bkz. I tried max_time and max_loops, but it seems to have no effect. For example, I set:

`param20.flags |= BKZ_VERBOSE;
param20.max_loops = 1;`

and call

`bkz_reduction 	(&m_tored, &U,  param20, FT_DEFAULT, 0);`

Then, my output is:

> block size:  20, flags: 0x0001, max_loops:   1, max_time: 0.0, autoAbort: (     -,  -),
Block [1-   1] BKZ-20 reduced for the first time
End of BKZ loop    0, time =     0.022s, r_0 = 9.99e7, slope = -0.116176, log2(nodes) = 16.309618
End of BKZ loop    1, time =     0.041s, r_0 = 2.43e7, slope = -0.097066, log2(nodes) = 17.475393
Block [1-   2] BKZ-20 reduced for the first time
End of BKZ loop    2, time =     0.059s, r_0 = 2.43e7, slope = -0.084475, log2(nodes) = 18.063084
End of BKZ loop    3, time =     0.075s, r_0 = 1.70e7, slope = -0.075087, log2(nodes) = 18.518265
Block [1-   3] BKZ-20 reduced for the first time
End of BKZ loop    4, time =     0.089s, r_0 = 1.70e7, slope = -0.070251, log2(nodes) = 18.837714
End of BKZ loop    5, time =     0.105s, r_0 = 1.31e7, slope = -0.066106, log2(nodes) = 19.126750
End of BKZ loop    6, time =     0.117s, r_0 = 1.31e7, slope = -0.063244, log2(nodes) = 19.299657
Block [1-  55] BKZ-20 reduced for the first time
End of BKZ loop    7, time =     0.129s, r_0 = 9.86e6, slope = -0.062599, log2(nodes) = 19.436663
End of BKZ loop    8, time =     0.140s, r_0 = 9.86e6, slope = -0.061867, log2(nodes) = 19.515519
End of BKZ loop    9, time =     0.149s, r_0 = 9.86e6, slope = -0.061302, log2(nodes) = 19.596748
End of BKZ loop   10, time =     0.159s, r_0 = 9.86e6, slope = -0.060946, log2(nodes) = 19.663780
Block [1-  56] BKZ-20 reduced for the first time
Block [1-  57] BKZ-20 reduced for the first time
Block [1-  58] BKZ-20 reduced for the first time
Block [1-  59] BKZ-20 reduced for the first time
Block [1-  60] BKZ-20 reduced for the first time
Block [1-  61] BKZ-20 reduced for the first time
Block [1-  62] BKZ-20 reduced for the first time
Block [1-  63] BKZ-20 reduced for the first time
Block [1-  64] BKZ-20 reduced for the first time
Block [1-  65] BKZ-20 reduced for the first time
Block [1-  66] BKZ-20 reduced for the first time
Block [1-  67] BKZ-20 reduced for the first time
Block [1-  68] BKZ-20 reduced for the first time
Block [1-  69] BKZ-20 reduced for the first time
Block [1-  70] BKZ-20 reduced for the first time
Block [1-  71] BKZ-20 reduced for the first time
Block [1-  72] BKZ-20 reduced for the first time
Block [1-  73] BKZ-20 reduced for the first time
End of BKZ loop   11, time =     0.167s, r_0 = 9.86e6, slope = -0.060973, log2(nodes) = 19.711008
End of BKZ loop   12, time =     0.175s, r_0 = 9.86e6, slope = -0.060481, log2(nodes) = 19.762969
End of BKZ loop   13, time =     0.185s, r_0 = 9.86e6, slope = -0.060145, log2(nodes) = 19.823308
End of BKZ loop   14, time =     0.190s, r_0 = 9.86e6, slope = -0.060145, log2(nodes) = 19.856500
End of BKZ: success

So 14 loops are executed? Or are there different types of "loop"s? Similar for max_time. If I set it to 0.2 seconds, I also get the same number of loops and an overall bkz-time of 0.8 seconds (for bigger examples the same).
Do I have to set other parameters to get the abortion working? 
Thanks in advance!

**Comment by malb** [comment]
You need to set the flags `BKZ.MAX_LOOPS` and `BKZ.MAX_TIME` as well. Not the most intuitive interface, I know. PRs welcome :)
