### ISSUE TITLE
Lack of documentation to use fplll as a library

### ISSUE THREAD

**Issue by marinthiercelin** [fplll/fplll#367]
In the documentation:
The part "How to use/How to use as a library" just gives a link that points back to the same page.
For now the only thing that comes close to documentation are the test files. 
It would be useful to have some documentation that would let us have something as simple to use as `fplll -a svp [matrix]` directly in the code.
As of now, it is a bit unclear how to set up the parameters, based solely on the test files.

**Comment by malb** [comment]
The link does not take you right back to the same page, it does take you to the API documentation as advertised: see links at the top of the page. Of course, PRs on more high-level documentation welcome.

**Comment by marinthiercelin** [comment]
> The link does not take you right back to the same page, it does take you to the API documentation as advertised: see links at the top of the page
Yes but once you get to the API Documentation, and go to the same part "How to use as library", you get the same link, and still no explanation of how to use it as a library.
