### ISSUE TITLE
Unknown reference [S09] in README

### ISSUE THREAD

**Issue by christianpeel** [fplll/fplll#371]
The [S09] link in the README describing the first type of 'latticegen' is not found in the bibliography. 
> generates a knapsack like matrix of dimension d x (d+1) and b bits (see, e.g., [S09])

It's likely obvious to gurus in the space what this reference should be, but I'm not a lattice reduction guru. Would it be possible to get a better reference?

**Comment by malb** [comment]
See https://groups.google.com/d/msg/fplll-devel/G8sq-4n2hew/sIb3uoO3AgAJ
