### ISSUE TITLE
Race condition in thread_pool

### ISSUE THREAD

**Issue by jamesjer** [fplll/fplll#399]
See https://github.com/cr-marcstevens/snippets/pull/1.  This manifested on the 32-bit x86 build for Fedora, where simply attempting to run "help2man -N -o ../latsieve.1 ./latsieve" to generate a man page for latsieve led to a hang.  I could repeat this on the command line.  Repeatedly running "latsieve --help" in a loop invariably led to a hang after a few iterations.

**Comment by cr-marcstevens** [comment]
Can confirm: thread_pool possibly hangs when programs exit very quickly.

This has been fixed, I'll make a PR for the updated thread_pool.

**Comment by cr-marcstevens** [comment]
Thanks for reporting the issue!
The fix has been merged, so closing this issue.
