### ISSUE TITLE
constructor of `BKZParam` may have a mistake

### ISSUE THREAD

**Issue by LunaLuan9555** [fplll/fplll#401]
In bkz_param.h, line 114:
`double gh_factor               = BKZ_DEF_AUTO_ABORT_MAX_NO_DEC,`
according to defs.h and the description of BKZ 2.0, it may be modified to 
`double gh_factor = BKZ_DEF_GH_FACTOR,` ? 
@malb

**Comment by malb** [comment]
Ta!
