### ISSUE TITLE
Support ternary --with-qd

### ISSUE THREAD

**Issue by orlitzky** [fplll/fplll#405]
I'm packaging fplll for Gentoo, and the `--with-qd` flag is giving me some trouble. Right now the flag supports two things:

* Disabling the support via `--without-qd`. This works OK.
* Enabling the support via `--with-qd=PATH`. This only sort-of works.

The main problem with `--with-qd=PATH` is that there's no way for me to set the path to the right place if the libraries are in e.g. `/usr/lib64` and the headers in `/usr/include`. If `/usr/lib` points to 32-bit libraries on a multilib system, passing `--with-qd=/usr` will try to link those 32-bit libraries into a 64-bit fplll. No bueno.

On the other hand, if I _don't_ supply the path, then the bare `--with-qd` sets the path to the literal value "yes". And that doesn't work, because there are no libraries in `yes/lib`.

Would it be possible to add another case for `x$with_qd = "xyes"`, that will use the standard system locations for the library and headers? That would avoid the first problem in my case: if you do an AC_SEARCH_LIBS on a 64 bit system, it should only find 64 bit libs.

**Comment by malb** [comment]
I agree, this should be done. Any chance you could provide a PR? Otherwise, I'll try to get around to it when I can.
