### ISSUE TITLE
Problem with compilling

### ISSUE THREAD

**Issue by tiagomendes7** [fplll/fplll#408]
Cant compile the files in Make by hand.

When i execute the "make check" it compiles all the files in tests folder but when i execute in the terminal the command "g++ -o out test_bkz.cpp" it says :

"test_bkz.cpp:16:10: fatal error: 'io/json.hpp' file not found"

I am working in a Mac with OS Catalina version 10.15.3

How can i fix it ?

**Comment by malb** [comment]
See e.g. https://stackoverflow.com/questions/11698478/include-an-external-library-in-c
