### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by tiagomendes7** [fplll/fplll#409]
Tried what you said Martin. Now i have this problem:

"ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

with this command:

"g++ -L/usr/local/lib/ -I/usr/local/include/ -std=c++11 -o output tests.cpp"

**Comment by malb** [comment]
This is quite old now, assuming it's stale and closing for now.
