### ISSUE TITLE
windows 10 ./configure issue

### ISSUE THREAD

**Issue by andrew-young** [fplll/fplll#410]
./configure: line 17558: syntax error near unexpected token `LIBQD,'
./configure: line 17558: `  PKG_CHECK_MODULES(LIBQD, qd, have_libqd="yes",'

solved with:
sudo apt-get install pkg-config
I apologize in advance if I simply missed this step somewhere, but I think it should be added to the install instructions.

**Comment by malb** [comment]
Ah, this is a side effect of https://github.com/fplll/fplll/pull/407. We should either require `pkg-config` explicitly or make it optional there.

**Comment by zhangT90A** [comment]
I met a strange problem. Although my computer successfully  excute command 'make' , I still met an error. 
make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
============================================================================
Testsuite summary for fplll 5.3.2
============================================================================
# TOTAL: 13
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [Makefile:854: test-suite.log] Error 1
make[3]: Leaving directory '/mnt/c/fplll-master/tests'
make[2]: *** [Makefile:962: check-TESTS] Error 2
make[2]: Leaving directory '/mnt/c/fplll-master/tests'
make[1]: *** [Makefile:1120: check-am] Error 2
make[1]: Leaving directory '/mnt/c/fplll-master/tests'

**Comment by zhangT90A** [comment]
I met a strange problem. Although my computer successfully excute command 'make' , I still met an error.
make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
Testsuite summary for fplll 5.3.2
TOTAL: 13
PASS: 0
SKIP: 0
XFAIL: 0
FAIL: 13
XPASS: 0
ERROR: 0
============================================================================
See tests/test-suite.log
make[3]: *** [Makefile:854: test-suite.log] Error 1
make[3]: Leaving directory '/mnt/c/fplll-master/tests'
make[2]: *** [Makefile:962: check-TESTS] Error 2
make[2]: Leaving directory '/mnt/c/fplll-master/tests'
make[1]: *** [Makefile:1120: check-am] Error 2
make[1]: Leaving directory '/mnt/c/fplll-master/tests'

**Comment by zhangT90A** [comment]
I met a strange problem. Although my computer successfully excute command 'make' , I still met an error, which told me that my fplll cannot work.
make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
Testsuite summary for fplll 5.3.2
TOTAL: 13
PASS: 0
SKIP: 0
XFAIL: 0
FAIL: 13
XPASS: 0
ERROR: 0

**Comment by zhangT90A** [comment]
I met a strange problem. Although my computer successfully excute command 'make' , I still met an error as follow, which told me that my fplll cannot work. 
make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
Testsuite summary for fplll 5.3.2
TOTAL: 13
PASS: 0
SKIP: 0
XFAIL: 0
FAIL: 13
XPASS: 0
ERROR: 0

**Comment by shi-bai** [comment]
Hi zhangT90A,

> Although my computer successfully excute command 'make

Did you have the binaries like fplll and latticegen made?

Could you attach the full output after "make check"?

**Comment by zhangT90A** [comment]
> Hi zhangT90A,
> 
> > Although my computer successfully excute command 'make
> 
> Did you have the binaries like fplll and latticegen made?
> 
> Could you attach the full output after "make check"?

Thank you for your reply. I have already fix this issue.
 In document test-suite.log which record mistake of command 'make check', compiler remind me that "libqd.so.0--cannot open shared object file: No such file or directory". Therefore I find the location of libqd.so.0 and changed LD_LIBRARY_PATH, then excute command "sudo ldconfig". After those, my fplll was completely installed.
