### ISSUE TITLE
Creating a matrix with mpz_t elements

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#414]
I wish to create and use a matrix consisting of mpz_t elements. Whilst I can create the matrix OK and even fill it with zeros - when I come to assign an element with a mpz_t integer I get a compilation error as shown below.  How do I get to assign a value to one of the elements?

/usr/bin/g++-4.8 -std=c++11 -ldl  -o fplll_example.o -c -I/usr/local/include/fplll fplll_example.cpp
fplll_example.cpp: In function ‘int main()’:
fplll_example.cpp:31:36: error: no matching function for call to ‘fplll::Z_NR<__mpz_struct [1]>::Z_NR(mpz_t)’
   lattice[i][i] = Z_NR<mpz_t>(order);
                                    ^
fplll_example.cpp:31:36: note: candidates are:
In file included from /usr/local/include/fplll/nr/nr.h:15:0,
                 from /usr/local/include/fplll/nr/numvect.h:19,
                 from /usr/local/include/fplll/nr/matrix.h:21,
                 from /usr/local/include/fplll/gso_interface.h:22,
                 from /usr/local/include/fplll/gso.h:21,
                 from /usr/local/include/fplll/lll.h:21,
                 from /usr/local/include/fplll/pruner/pruner.h:21,
                 from /usr/local/include/fplll/bkz_param.h:24,
                 from /usr/local/include/fplll/bkz.h:21,
                 from /usr/local/include/fplll/fplll.h:25,
                 from fplll_example.cpp:7:
/usr/local/include/fplll/nr/nr_Z_mpz.inl:13:20: note: fplll::Z_NR<Z>::Z_NR(const fplll::Z_NR<Z>&) [with Z = __mpz_struct [1]]
 template <> inline Z_NR<mpz_t>::Z_NR(const Z_NR<mpz_t> &z) { mpz_init_set(data, z.data); }
                    ^
/usr/local/include/fplll/nr/nr_Z_mpz.inl:13:20: note:   no known conversion for argument 1 from ‘mpz_t {aka __mpz_struct [1]}’ to ‘const fplll::Z_NR<__mpz_struct [1]>&’
/usr/local/include/fplll/nr/nr_Z_mpz.inl:11:20: note: fplll::Z_NR<Z>::Z_NR() [with Z = __mpz_struct [1]]
 template <> inline Z_NR<mpz_t>::Z_NR() { mpz_init(data); }
                    ^
/usr/local/include/fplll/nr/nr_Z_mpz.inl:11:20: note:   candidate expects 0 arguments, 1 provided
makefile:16: recipe for target 'fplll_example.o' failed

[fplll_example.txt](https://github.com/fplll/fplll/files/4423434/fplll_example.txt)

**Comment by malb** [comment]
This works for me:

```C++
#include <fplll.h>
#include <fplll/nr/nr.h>
#include <fplll/nr/matrix.h>
using namespace std;
using namespace fplll;
#define MAX_DIMENSION 5
int main() {
	ZZ_mat<mpz_t> lattice = ZZ_mat<mpz_t>(MAX_DIMENSION, MAX_DIMENSION);
	mpz_t order;
	mpz_init (order);
	mpz_set_ui(order,1);
	lattice.fill(0);
	for (int i=0; i < MAX_DIMENSION; i++){
		lattice[i][i] = order;
	}
}
```

**Comment by johughes99** [comment]
What version of gcc and C++ did you use?

**Comment by malb** [comment]
` gcc -lstdc++ -lgmp -lmpfr -lfplll -L$VIRTUAL_ENV/lib -I$VIRTUAL_ENV/include  fplll_test.cpp -o fplll_test` with `gcc (Debian 8.3.0-6) 8.3.0`

**Comment by johughes99** [comment]
tried gcc 8.4 and -lstdc++ - still same error.  Let me rebuild fplll from scratch and triy again

**Comment by johughes99** [comment]
what version is GMP fplll built with?

**Comment by johughes99** [comment]
OK - eventually got it to work.  Although not sure exactly why.  The final step that seems to sort it was I did:

   lattice[i][i] = order;
 
rather than

  lattice[i][i]  = Z_NR<mpz>order;

but I also made sure I built gmp 6.2.0 with gcc 8.4 and fplll with 8.4 - previously was building it with 7.5,
