### ISSUE TITLE
Accessing an element in a Matrixi

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#416]
I need to extract the value of an element in a Matrix.

I had hoped the call

`mpz_t element = lattice[i][j];`

would work. Where

lattice is define as ZZ_mat<mpz_t> 

instead I got the error:

`pkcs11_ec_ecdsaAttacks.cpp:191:32: error: array must be initialized with a brace-enclosed initializer
    mpz_t element = lattice[i][j] ;`

**Comment by malb** [comment]
Works for me:

```c++
#include <fplll.h>
#include <fplll/nr/nr.h>
#include <fplll/nr/matrix.h>


using namespace std;
using namespace fplll;

#define MAX_DIMENSION 5

int main() {

	// create lattice
	ZZ_mat<mpz_t> lattice = ZZ_mat<mpz_t>(MAX_DIMENSION, MAX_DIMENSION);
	Z_NR<mpz_t> order;
	order = 1;

	// make sure lattice is empty
	lattice.fill(0);

	for (int i=0; i < MAX_DIMENSION; i++){
		lattice[i][i] = order;
	}

	int status;   // zero on success
	status = lll_reduction(lattice, LLL_DEF_DELTA, LLL_DEF_ETA, LM_PROVED, FT_MPFR, 0, LLL_DEFAULT);
	if (status != RED_SUCCESS)
	{
		cout << "ERROR: " << status << endl;
		exit(1);
	}

	order = lattice[1][1];

	cout << "test finished" << endl;

}
```

Compiled with
```
gcc -I$VIRTUAL_ENV/include -lstdc++ `pkg-config --libs fplll` fplll_example.cc -o fplll_example 
```

**Comment by johughes99** [comment]
Thanks Martin. That works for me. I had expected that each element in the matrix was of type mpz_t - when in fact it is of type Z_NR<mpz_t>. The documentation wasn't really clear on that nor any of the tests included an example of this.

Also what confused me as well wasi n the Matrix,T> Class Template Reference the () operator was being overloaded such that calls like (i,j) were being permitted as well.
