### ISSUE TITLE
A new  Z_NR<mpz>constructor?

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#417]
I want to create an object of type Z_NR<mpz_t> and then assign it a value from a mpz_t object.

I had hoped that there was a Z_NR<mpz_t> constructor to do something like:

`	mpz_t tmp_mpz;
	mpz_init (tmp_mpz);
	// assign zValue with the value of tmp_mpz
	Z_NR<mpz_t> zValue = Z_NR<mpz_t>(tmp_mpz);`

However, this does not seem to be possible. 

Of course, something like:

`	Z_NR<mpz_t> zOrder = Z_NR<mpz_t>();
	zOrder = tmp_mpz;`

works fine. But having a constructor to do this would be nicer.

**Comment by malb** [comment]
I agree this would be good to have. PRs welcome :)

**Comment by johughes99** [comment]
Maybe - when I get more familar with the code.

Also, it would be nice to have a modulus operator on integers of type Z_NR - as I couldn't find one.

**Comment by joerowell** [comment]
@malb This can be closed, right? It's now in master as of #422.
