### ISSUE TITLE
add `-latomic` when needed

### ISSUE THREAD

**Issue by IvaKom** [fplll/fplll#418]
The compilation on an armhf machine (RPi4) fails with
```
/usr/bin/ld: ./.libs/libfplll.so: undefined reference to `__atomic_store_8'                                                                     /usr/bin/ld: ./.libs/libfplll.so: undefined reference to `__atomic_load_8'
```
Apparently it needs to be linked with `libatomic`. Adding `LDFLAGS="$LDFLAGS -latomic"` to `configure.ac` solves the issue for me. Sagemath has recently updated the version of fplll it uses and as of it is broken on armhf too.
gcc 8.3.0

**Comment by malb** [comment]
Yes, looks like we should add it. @cr-marcstevens do you agree?

**Comment by cr-marcstevens** [comment]
I agree, but this probably has to be done in an m4 as it's platform dependent. I guess ax_pthread.m4, or we should create an ax_atomic.m4 from scratch.

**Comment by malb** [comment]
Good point. Googling around found https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797228  which we could use.

**Comment by cr-marcstevens** [comment]
Yes, it seems like the following m4 file would do the trick:
https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/m4/check_atomic.m4?revision=7788&view=markup
