### ISSUE TITLE
BKZ - different results between fplll and fpylll

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#420]
I'm "porting" some python code which uses fpylll to use C++ and fplll. I also have some test data - so I can compare exactly the results between the two. 

Having created a ZZ_mat<mpz_t> matrix (being of dimensions of 5x5 to begin with I can compare line by line the results of the operations on the matrix).

The first operation is a LLL reduction - and that works fine - giving the results I expect. I also do a GSO - again this is fine. However, when I come to do a BKZ reduction - this is where the problems start.

Whilst most of the rows have the values I expect - some of them don't.  Given that fpylll is just a python interface to fplll I had  expected the same results. Hence, my thought is whether I'm calling the BKZ function with the correct parameters:

In python the call is:

`BKZ.reduction(lattice, BKZ.Param(block_size=block_size, strategies=BKZ.DEFAULT_STRATEGY, auto_abort=True)`

In C++ my call is:

`bkz_reduction(*lattice, blockSize, BKZ_DEFAULT, FT_DEFAULT, 0);`

the failure I'm seeing is with BKZ-15

**Comment by malb** [comment]
Those aren't equivalent, you need to call

```
int bkz_reduction(ZZ_mat<mpz_t> *B, ZZ_mat<mpz_t> *U, const BKZParam &param,
                  FloatType float_type = FT_DEFAULT, int precision = 0);
```

See e.g. https://github.com/fplll/fplll/blob/master/tests/test_bkz.cpp#L156 for an example.

**Comment by johughes99** [comment]
I actually do this now anyway and did look at the example. I call it as follows

`		vector<Strategy> strategies;
		BKZParam param(blockSize, strategies);

		param.flags = BKZ_DEFAULT|BKZ_AUTO_ABORT;

		status = bkz_reduction(lattice, NULL, param ,FT_DEFAULT, 0);`

My questions is how the params be set up so its equivalent to the fyplll call?
