### ISSUE TITLE
LLL Reduction - differences between fplll and fpylll

### ISSUE THREAD

**Issue by johughes99** [fplll/fplll#425]
I am comparing the results of doing LLL reduction on a lattice  between fplll and fpylll

What I have noticed is that at dimensions of 50 and 60 after the lattice is lll reduced the contents of the lattice is identical for both fplll and fpylll.  But at dimensions of 80 and above the lll reduced lattice is different between these two libraries.  For fplll each cell contains a mpz_t number

My fplll code is:

`status = lll_reduction(*lattice, LLL_DEF_DELTA, LLL_DEF_ETA, LM_PROVED, FT_MPFR, 0, LLL_DEFAULT);`

and the fpylll code is:

`LLL.reduction(lattice)`

I have also tried – without success - the following calls in fplll:

`status` = `lll_reduction(*lattice, 0.99, 0.51, LM_WRAPPER, FT_DEFAULT, 0, 0);`

as well as:

`status` = `lll_reduction(*lattice);`

So my question is what parameters should I use in my fplll C/C++ code to mirror exactly the fpylll results.

**Comment by shi-bai** [comment]
Hi johughes99, could you attach the input lattice used in fpYlll so we can try to debug?

**Comment by johughes99** [comment]
Sure - I will get something to you tomorrow

**Comment by johughes99** [comment]
In preparing the data for this I noticed a very small "bug" in my code that meant the input lattice was not 100% the same as used for both fplll and fyplll. My visual inspection had shown they were the same - obviously they were not.

So on fixing the bug I can conform LLL reduction gives the same result for both.

Sorry about the confusion!
