### ISSUE TITLE
windows 10 make issue 

### ISSUE THREAD

**Issue by zhangT90A** [fplll/fplll#426]
make[3]: Entering directory '/mnt/c/fplll-master/fplll'
  CXXLD    libfplll.la
/usr/bin/ld: /usr/local/lib/libqd.a(dd_real.o): relocation R_X86_64_PC32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1147: libfplll.la] Error 1
make[3]: Leaving directory '/mnt/c/fplll-master/fplll'
make[2]: *** [Makefile:900: all] Error 2
make[2]: Leaving directory '/mnt/c/fplll-master/fplll'
make[1]: *** [Makefile:498: all-recursive] Error 1
make[1]: Leaving directory '/mnt/c/fplll-master'
make: *** [Makefile:386: all] Error 2

All the base required in instruction has been installed， such as GNU, autotools, g++,  MPFR, pkg-config and QD.
command './configure' succeed, while excuting command 'make' didn`t go through.

**Comment by malb** [comment]
You need to build libqd with `--enabled-shared`

**Comment by zhangT90A** [comment]
Under your guidance， I solve that problem with command --enabled-shared. And there is a new problem while excuting command 'make check'.

make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
============================================================================
Testsuite summary for fplll 5.3.2
============================================================================
# TOTAL: 13
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [Makefile:854: test-suite.log] Error 1
make[3]: Leaving directory '/mnt/c/fplll-master/tests'
make[2]: *** [Makefile:962: check-TESTS] Error 2
make[2]: Leaving directory '/mnt/c/fplll-master/tests'
make[1]: *** [Makefile:1120: check-am] Error 2
make[1]: Leaving directory '/mnt/c/fplll-master/tests'
make: *** [Makefile:498: check-recursive] Error 1

**Comment by zhangT90A** [comment]
Thank you. Now I make it.But I met a strange problem. Although my computer successfully excute command 'make' , I still met an error as follow, which told me that my fplll cannot  @malb 
make[3]: Entering directory '/mnt/c/fplll-master/tests'
FAIL: test_nr
FAIL: test_lll
FAIL: test_enum
FAIL: test_cvp
FAIL: test_svp
FAIL: test_bkz
FAIL: test_pruner
FAIL: test_sieve
FAIL: test_gso
FAIL: test_lll_gram
FAIL: test_hlll
FAIL: test_svp_gram
FAIL: test_bkz_gram
Testsuite summary for fplll 5.3.2
TOTAL: 13
PASS: 0
SKIP: 0
XFAIL: 0
FAIL: 13
XPASS: 0
ERROR: 0
