### ISSUE TITLE
./configure issue in Linux

### ISSUE THREAD

**Issue by audrey-cauchy** [fplll/fplll#427]
When I ./configure the fplll in Linux, I face the similar problem which is mentioned by #410 . To solve this problem, I update  pkg-config to the latest versions and configure the QD with optional --enable-shared=yes. But the result is negative. The problem still exists. I hope someone can give me some advice:
./configure: line 17558: syntax error near unexpected token LIBQD,' ./configure: line 17558: PKG_CHECK_MODULES(LIBQD, qd, have_libqd="yes",'

**Comment by shi-bai** [comment]
I have no clue then .. did you try to clean everything and start from scratch again?

**Comment by alberthendriks** [comment]
I had the same issue on linux (but with a different line number), even after `sudo apt-get install pkg-config`. To solve it, I deleted an re-cloned the project and then checked out the latest release(!) instead of the master branch. `git checkout tags/<version> -b <version>`

**Comment by malb** [comment]
Seems resolved, kinda.
