### ISSUE TITLE
Switch from mpz_t to mpz_class

### ISSUE THREAD

**Issue by joerowell** [fplll/fplll#429]
Not a bug per se, but an attempt to solicit opinion.

At the moment fplll uses ```mpz_t ``` throughout the library in various different places.
Instead, it might be nicer to use the C++ wrapper class - ```mpz_class``` - which ships with GMP. The documentation can be found at: https://gmplib.org/manual/C_002b_002b-Interface-Integers.html. 

The reasoning behind this is that ```mpz_class``` contains all of the nice C++ features that we might expect. This tends to allow for more natural usage. 

For example, one can simply write:

```mpz_class x = 5;``` 

With this, the amount of precision will be automatically derived, but without the need to call ```mpz_init``` first. This makes it more "C++ like".  We can, of course, still manually set the precision as with ```mpz_t```. 

The other main benefit is that the ```mpz_class``` comes with destructors too; so, as opposed to having to call ```mpz_free```, we can use stack-based semantics and let C++ tidy it up for us. This fits in more neatly with the rest of the library - I believe that ```mpz_t``` and ```mpfr_t``` are the only types where explicit creation and deletion are required. Note that ```mpfr_t``` doesn't have an equivalent class that ships directly with ```mpfr```, so this would cause some disunity between these types.

I'm happy to implement this myself, I just wanted to see if this is seen as a worthwhile change.

**Comment by shi-bai** [comment]
Hi Joe,

Thanks for the suggestion. We didn't seem to use mpz_t directly in the code. For example, in all the *.cpp files, the "mpz_t" and "mpz_init" is not used directly. Instead, something lilke

Z_NR<mpz_t> x; 

is used. Here the Z_NR class is like a homebrewed version of the mpz_class.

**Comment by joerowell** [comment]
Hi Shi,

Good point. I seemed to think that directly using mpz_t was more common than it actually was... thanks!
