### ISSUE TITLE
enable/disable maintainer mode

### ISSUE THREAD

**Issue by dimpase** [fplll/fplll#439]
autconf projects are very sensitive to skew clocks, something that people who have to build on HPC systems come to quite often.

Could we add AM_MAINTAINTER_MODE to configure.ac  (that's all what it takes, IIRC) ?

**Comment by malb** [comment]
So this is just to add

```
AM_MAINTAINER_MODE([enable])
```

which doesn't change the behaviour but adds `--disable-maintainer-mode`?

**Comment by dimpase** [comment]
yes
