### ISSUE TITLE
make check defaults to installed version of fplll

### ISSUE THREAD

**Issue by joerowell** [fplll/fplll#441]
## Issue:

If one has fplll installed on their local machine then running ``make check``  defaults to linking against the installed version, as opposed to the version in the current directory. I guess this is to do with the behaviour of PATH?

## How to replicate:
I discovered this whilst writing tests for my pull request (#440). This behaviour has been confirmed on a few different machines.

If one installs fplll locally (say, v5.3.3), then clones the most recent version of the pull request and runs ``make check``, the tests will fail (as the templates can't be found).

However, if one installs the most recent version of the pull request via ``make install`` then all of the tests will pass.

**Comment by malb** [comment]
This is confusing, we do compile with `rpath` set:
```
libtool: link: g++ -std=c++11 -O3 -Wall -Wl,-rpath -Wl,/home/malb/Projects/lattices/fplll/fplll/.libs -o test_bkz_gram test_bkz_gram.o  -L/home/malb/Projects/lattices/fplll/fplll/.libs /home/malb/Projects/lattices/fplll/fplll/.libs/libfplll.so -lqd -lmpfr -lgmp -pthread -Wl,-rpath -Wl,/home/malb/Projects/lattices/fplll/fplll/.libs
```

**Comment by malb** [comment]
Can I close this?

**Comment by joerowell** [comment]
Turns out I can't replicate this bug. Closing it.
