### ISSUE TITLE
fesetround is not a member of std

### ISSUE THREAD

**Issue by andreas-enge** [fplll/fplll#444]
Hello,

compiling a trivial program containing "#include <fplll.h>" fails with the following error message:

/gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/enum/enumerate_base.h: In member function 'void fplll::EnumerationBase::restore_rounding()':
/gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/enum/enumerate_base.h:133:34: error: 'fesetround' is not a member of 'std'; did you mean 'fesetround'?
  133 |   void restore_rounding() { std::fesetround(rounding_backup); }
      |                                  ^~~~~~~~~~
In file included from /home/enge/.guix-profile/include/c++/fenv.h:36,
                 from /home/enge/.guix-profile/include/c++/cfenv:41,
                 from /gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/enum/enumerate_base.h:25,
                 from /gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/enum/enumerate.h:23,
                 from /gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/bkz.h:22,
                 from /gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll/fplll.h:25,
                 from /gnu/store/9dmvkqhvy33wqzsh85gdxwys07anj0qy-fplll-5.3.3/include/fplll.h:1,
                 from test.c:1:
/home/enge/.guix-profile/include/fenv.h:107:12: note: 'fesetround' declared here
  107 | extern int fesetround (int __rounding_direction) __THROW;
      |            ^~~~~~~~~~

repeated a few times, and similar ones for fegetround. I tried adding "--std=c++11", "--std=c__14" or "--std=c++17", but to no avail. 

g++ --version
g++ (GCC) 10.2.0

glibc 2.31

fenv.h contains this:
#if _GLIBCXX_HAVE_FENV_H
#include_next <fenv.h>
#endif
#if _GLIBCXX_USE_C99_FENV_TR1
...
#undef fesetround
...
namespace std
{
...
  using ::fesetround;

So I suppose _GLIBCXX_USE_C99_FENV_TR1 is not defined in my context, but that looks very glibc internal...

Andreas

**Comment by jengelh** [comment]
“The <fenv.h> header shall define each of the following macros _if and only if_ the implementation supports getting and setting the represented rounding direction by means of the fegetround() and fesetround() functions.”

Now, since everyone seems to be on a x86_64-linux-gnu like system, I see no reaso not to have fesetround other than it being willfully disabled, since it's a build-time thing, e.g.:

```
/usr/include/c++/10/x86_64-suse-linux/bits/c++config.h:#define _GLIBCXX_USE_C99_FENV_TR1 1
```

```
» g++ -std=c++11 -dM -x c++ -E x.cpp | grep FENV
#define _GLIBCXX_CFENV 1
#define _GLIBCXX_FENV_H 1
#define _FENV_H 1
#define _GLIBCXX_HAVE_FENV_H 1
#define _GLIBCXX_USE_C99_FENV_TR1 1
```

**Comment by andreas-enge** [comment]
I see the exact same lines except for the last one.

And my include/c++/x86_64-unknown-linux-gnu/bits/c++config.h has this:
#define _GLIBCXX_HAVE_FENV_H 1
/* Define if C99 functions in <fenv.h> should be imported in <tr1/cfenv> in
   namespace std::tr1. */
/* #undef _GLIBCXX_USE_C99_FENV_TR1 */

The functions are defined, just not in the namespace std - replacing std:fe[g|s]etround by fe[g|s]round solves the problem for me. Not importing them into the namespace std::tr1 seems reasonable to me, but this apparently implies that they are not imported into std either.

**Comment by joerowell** [comment]
Hi, could you please provide an example of a program that produces this error? This might help us debug it. Thanks!

**Comment by jengelh** [comment]
When building gcc(-10.x), it will check whether fenv.h (a C99 header) is available and exposes its contents to a C++98 compiler. I see no indication _in glibc_ that it would care whether it is being used under `__cplusplus` or not, but maybe your guix compiler was bootstrapped on a different libc or run into some other kind of problem.

```
gcc» ./configure
[...]
checking for ISO C99 support to TR1 in <fenv.h>... yes
```

**Comment by andreas-enge** [comment]
Hello joerowell,

it is really the simplest program one can imagine:
#include <fplll.h>
int main() {
   return 1;
}

Now I am not a C++ programmer, but from what I understand, the C++11 standard contains std::fesetround and std::fegetround? My compiler provides only festround and fegetround; but if the standard says otherwise, this may be a problem with the way we compile gcc/g++ in Guix, I should bring up the issue there, and it can be closed here.

**Comment by cr-marcstevens** [comment]
Hi Andreas,

Yes, in all C++ reference documentation I can find it appears include header <cfenv> (which fplll uses) should define std::fesetround and std::fegetround for C++11 and later.

**Comment by andreas-enge** [comment]
Okay, then the problem is on my side, and I am closing this issue. Sorry for the bother, and thanks for your time and your help!

Andreas
