### ISSUE TITLE
Lack of library documentation

### ISSUE THREAD

**Issue by andreas-enge** [fplll/fplll#445]
At https://github.com/fplll/fplll#how-to-use-as-a-library the text
"See API documentation."
links to https://fplll.github.io/fplll/
and there the text "See API documentation" links to the same web page again.

Andreas

**Comment by malb** [comment]
Click around at  https://fplll.github.io/fplll/

**Comment by emmanuelthome** [comment]
Hi Martin,

There might be some misunderstanding. I agree that there is some info that can be accessed from the top panel at 
https://fplll.github.io/fplll ; I'm not sure of the recommended entry point to the API though. Is it https://fplll.github.io/fplll/namespacefplll.html ?

Also, I pretty much concur that the section

> How to use as a library
> See API documentation.

on that page has a circular link to itself (unrelated: href anchors are broken on that page, too).

Cheers,

E.

**Comment by emmanuelthome** [comment]
Thanks for the clarification. And yes, #413 and #367 and #359 are actually the same request (plus maybe more of that kind that I've missed)
