### ISSUE TITLE
Problem running on Ubuntu

### ISSUE THREAD

**Issue by ManolisDoulgerakis** [fplll/fplll#448]
Hi everyone,

I  recently tried to update fplll on my laptop to the latest version. 
I downloaded the source code as instructed, I then run
>./configure
>make 
>sudo make install

and all worked fine so far.
However, when I actually tried to use it, for example to run
>fplll basis.txt 
I received the following error
"fplll: error while loading shared libraries: libfplll.so.6: cannot open shared object file: No such file or directory"

I hope that this is not due to some stupid action on my side.
Did anybody else encounter such a behaviour?
Are there any suggestions on what might have gone wrong?

Thank you in advance.

Best,
Manos

**Comment by joerowell** [comment]
Manos and I fixed this:  it was an intermittent fault with his machine.

N.B to anyone who sees this in future; this can sometimes be resolved by running  ```sudo /sbin/ldconfig``` after the installation has completed. This simply updates the linker's cache.
