### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by pfasante** [fplll/fplll#46]
The documentation seems to be a bit deprecated.
When compiling the library from the github repo, the bkzReduction(BKZParam &) function does not exists anymore?

Also a brief description of what values these bkz parameters should typically be would be nice to have. E.g. when I want to control the precision, does the precision parameter corresponds to bits, is there an option to express "infinite" precision?

**Comment by pfasante** [comment]
The latest version does not seem to have a precision parameter at all, is the possibility to control it removed?

**Comment by malb** [comment]
I agree, this should be updated. Do you want to give it a try?

Note, however, that the precision parameter still is there https://github.com/dstehle/fplll/blob/master/src/fplll.h#L54  or am I misunderstanding your point? AFAIK, we have no "infinite" precision (i.e. increase until it doesn't bomb out any more) for BKZ, yet.

**Comment by pfasante** [comment]
Mh, I don't know how much spare time I'll find to do this. But I can give it a try nonetheless.

Oh and thanks for the pointer, I have overseen the default parameter :/ That should work fine.
Can you give me a hint, how the precision is handled? I.e. what is a reasonable choice for the precision parameter, how does precision=1 scale to precision=80 or so? Some rough information would be enough, so that I know in what range I should try my tests.

**Comment by malb** [comment]
Thanks for giving it a try. My strategy would be:

1. double (53 bits)
1a. long double (64 bits)
2. double double (106 bits)
3. mpfr (212 bits)
4. mpfr (414 bits)
...

until it works.

**Comment by pfasante** [comment]
Another question: Are you aware of any benchmarks comparing NTL and fplll BKZ implementation for lattices of dimension 100-300 and block sizes 20-25 or so? Maybe these would be interesting informations for the documentation as well (or at least including a link)?

**Comment by malb** [comment]
Hi, I don't know of such a comparison, but it would be good to have. Flint compared their LLL with fplll https://groups.google.com/d/msg/flint-devel/zdNBXow63z4/MWGWzl0xsTQJ 

I'd say, though, these kind of questions should perhaps be asked on fplll-devel, not in the comments of an unrelated ticket :)

**Comment by pfasante** [comment]
I agree, will write on fplll-devel.

**Comment by malb** [comment]
This ticket seems dormant. Close it?

**Comment by shi-bai** [comment]
agreed. closed.
