### ISSUE TITLE
Compiling with gcc-11 fails on Gentoo

### ISSUE THREAD

**Issue by kiwifb** [fplll/fplll#462]
A bug in Gentoo bugzilla has been opened earlier today
https://bugs.gentoo.org/show_bug.cgi?id=786858
```
                 from enum/enumerate.h:23,
                 from enum/enumerate.cpp:19:
../fplll/enum/enumerate_ext_api.h:87:25: error: ‘uint64_t’ is not a member of ‘std’; did you mean ‘wint_t’?
   87 | typedef std::array<std::uint64_t, FPLLL_EXTENUM_MAX_EXTENUM_DIM>(extenum_fc_enumerate)(
      |                         ^~~~~~~~
      |                         wint_t
../fplll/enum/enumerate_ext_api.h:87:25: error: ‘uint64_t’ is not a member of ‘std’; did you mean ‘wint_t’?
```
While it is not explicitly on https://gcc.gnu.org/gcc-11/porting_to.html it seems that `cstdint` may have to be included when compiling with gcc-11.

**Comment by malb** [comment]
Thanks. Looks like GCC-11 is so new not even the Docker images are updated yet. Will wait a bit until that changes to fix this, don't have GCC-11 here otherwise.

**Comment by kiwifb** [comment]
Well, since the PR is merged, I'll close this ticket.
