### ISSUE TITLE
error when make in the ubuntu 18.04

### ISSUE THREAD

**Issue by dragonlaaa** [fplll/fplll#471]
When I make the fplll-5.0 in the ubuntu 18.04 ，I have the follow massage：

/usr/bin/ld: //usr/local/lib/libqd.a(dd_real.o): relocation R_X86_64_PC32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status

      I find that above massage doesn't appear  when I make in the the WSL of win 10. Anyone else meet the same problem?

**Comment by cr-marcstevens** [comment]
Can you try the latest release?
https://github.com/fplll/fplll/releases/tag/5.4.1

**Comment by dragonlaaa** [comment]
I have just try the latest release 5.4.1 in my ubuntu 18.04, and have the same error : 
  CXXLD    libfplll.la
/usr/bin/ld: //usr/local/lib/libqd.a(dd_real.o): relocation R_X86_64_PC32 against symbol `_ZSt4cerr@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:895: recipe for target 'libfplll.la' failed
make[3]: *** [libfplll.la] Error 1

**Comment by malb** [comment]
Looks like you need to recompile `libqd` as a shared library with `-fPIC`.

**Comment by joerowell** [comment]
Also, please make sure that once you've followed @malb 's suggestion you then reconfigure fplll using: ``./configure --enable-shared=yes``

**Comment by dragonlaaa** [comment]
Thanks, I have solve it.
