### ISSUE TITLE
Common class names collide with Fplll. I suggest Fplll to have its own namespace.

### ISSUE THREAD

**Issue by lingerois** [fplll/fplll#476]
In my usage, I would like to use lattice algorithms in Fplll. However, I'd prefer to use my own database (e.g., Matrix). It I need to use algorithms from Fplll, I transfer my data to the datastructure of Fplll first. The problem is that, class names like Matrix is very common that might collide with the user's own classes.

I suggest Fplll to have its own namespace, to prevent name collision with its user.

This is just a suggestion, take it if you like. My work would go on well even if you don't take it. But I hight suggest Fplll to have its own namespace since the class names are too common and there's might be more user face the my problem in the future.

**Comment by joerowell** [comment]
fplll already has its own namespace: we start the header files with their own macro (```FPLLL_BEGIN_NAMESPACE```) that introduces the namespace. 

For example, see: https://github.com/fplll/fplll/blob/317f570a827d004afc7cc18d1fab7f9f34604cec/fplll/bkz.h#L26

**Comment by lingerois** [comment]
After I have posted this issue, I've check the code of Fplll again and realize I have made this mistake. I apologize for my arbitrary decision. Thank you joerowell for your patience.

My problem might be caused by some other reason. Thank you!
