### ISSUE TITLE
Class name collision with fplll.

### ISSUE THREAD

**Issue by lingerois** [fplll/fplll#477]
I have defined my own Matrix class. However, if I add
```
#include <fplll.h>
```
into my work, it has name collision with fplll.

I think this might caused by there's code like
```
using namespace fplll;
```
In the fplll library itself.

I hope you could help to figure out the right way to use fplll library in my C++ work.

**Comment by cr-marcstevens** [comment]
Could you point to that code `using namespace fplll` ?

BTW there is also a workaround for ambiguations by specifying the namespace where needed:
E.g. `my_namespace::Matrix` and `fplll::Matrix` instead of `Matrix`

**Comment by lingerois** [comment]
> Could you point to that code `using namespace fplll` ?
> 
> BTW there is also a workaround for ambiguations by specifying the namespace where needed:
> E.g. `my_namespace::Matrix` and `fplll::Matrix` instead of `Matrix`

Thanks. After precompile, I found code in the output file shown as following:
```
# 34 "/usr/local/include/fplll/fplll.h" 2 3
# 2 "/usr/local/include/fplll.h" 2 3
using namespace fplll;
```

Howevery, I know fplll.h doesn't contain such line of code. So this is what confused me. It might also be worthy to mention that I am using the release 5.4.1 version of fplll.

**Comment by lingerois** [comment]
The precompile translate
```C++
#include <fplll.h>
```
to the attached file
[out.txt](https://github.com/fplll/fplll/files/7185597/out.txt)
you can read out
```C++
using namespace fplll;
```
from line `85525`.

**Comment by joerowell** [comment]
I think this comes from this line:
https://github.com/fplll/fplll/blob/37bcab0caf510dd7ad49d8a3b277366d7b8b763a/fplll/Makefile.am#L127

I'm at a loss as for why this happens though. Maybe @malb knows?

**Comment by malb** [comment]
This seems bad and we should remove it, right?

**Comment by joerowell** [comment]
This should now be fixed. @lingerois could you please clone and install the most recent version of the repo and see if that helps? We'll probably have to release a new version to fix this for ```apt``` packages and similar, but that's above my pay-grade.

**Comment by lingerois** [comment]
Thanks for you effort! @joerowell It seems nice and well now :)
