### ISSUE TITLE
soname decreased in 5.4.3

### ISSUE THREAD

**Issue by antonio-rojas** [fplll/fplll#499]
The libfplll soname went *down* from 7 in version 5.4.2 to 6 in version 5.4.3. The library version was also decreased from 7.0.1 to 6.1.0.

**Comment by malb** [comment]
Odd, I increased it:

https://github.com/fplll/fplll/blob/master/configure.ac#L43

https://github.com/fplll/fplll/commit/af71387f96f3f094fb8774d9a041bb57e2b85be9

Is that not right? TBH, I never understood this soname business.

**Comment by antonio-rojas** [comment]
The soversion is `current-age`. If you follow the versioning rules from https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html this should never decrease.

**Comment by malb** [comment]
Ah, right, I misread those. Cutting the release again
