### ISSUE TITLE
Upload tarballs automatically from travis-ci

### ISSUE THREAD

**Issue by malb** [fplll/fplll#50]
We should use the appropriate [travis-ci API](https://docs.travis-ci.com/user/deployment/releases) to push the latest tarballs to GitHub.

**Comment by SnarkBoojum** [comment]
You shouldn't push tarballs to GitHub, but tag releases, and the tarballs will get generated from that.

**Comment by malb** [comment]
To generate tarballs with configure and friends pre-rendered, though, we need travis-ci or so for releases or commits.

**Comment by SnarkBoojum** [comment]
Well, if the releases could at least be tagged on github, that would still be helpful.
