### ISSUE TITLE
FPLLL_SONUM macro has no substitution

### ISSUE THREAD

**Issue by musicinmybrain** [fplll/fplll#509]
In `fplll/fplll_config.h.in`, the `FPLLL_SONUM` preprocessor macro is defined to have the value of the `@FPLLL_SONUM@`:

https://github.com/fplll/fplll/blob/3e10c51b31f29fca4a6b1e11494b96a5009dd19d/fplll/fplll_config.h.in#L16-L17

Since there is no `AC_SUBST([FPLLL_SONUM], ...)`, nothing is substituted here, and the template `@FPLLL_SONUM@` appears in the generated API header `fplll/fplll_config.h`.

Either this definition should be removed from the header, or an appropriate value should be defined with `AC_SUBST`. If you know what you want to do about this, I am happy to offer a PR.

This was originally reported [downstream in Fedora Linux](https://bugzilla.redhat.com/show_bug.cgi?id=2172617).

**Comment by malb** [comment]
Thanks. I guess we can remove the SONUM from the config header? But I have no strong preferences.
