### ISSUE TITLE
About the fplll library to implement the lll algorithm.

### ISSUE THREAD

**Issue by zlhlovelattice** [fplll/fplll#515]
Recently, I encountered problems when using the fplll library. May I ask whether the lll algorithm in the fplll library can be implemented under the infinite norm metric? I use the command   ./fplll mytxt.txt -a lll   output It seems to be measured under the Euclidean norm. If it can be realized under the infinite norm, can you write me a simple example in C++, thank you very much!

**Comment by shi-bai** [comment]
Hello,

You are right that the output vector is measured under the Euclidean norm. I am not aware of an implementation of LLL for infinite norm (there might some algorithms, but they are not implemented in fplll).

Cheers,
Shi

________________________________________
From: zlhlovelattice ***@***.***>
Sent: Wednesday, August 2, 2023 3:11 AM
To: fplll/fplll
Cc: Subscribed
Subject: [fplll/fplll] About the fplll library to implement the lll algorithm. (Issue #515)

                EXTERNAL EMAIL : Exercise caution when responding, opening links, or opening attachments.



Recently, I encountered problems when using the fplll library. May I ask whether the lll algorithm in the fplll library can be implemented under the infinite norm metric? I use the command ./fplll mytxt.txt -a lll output It seems to be measured under the Euclidean norm. If it can be realized under the infinite norm, can you write me a simple example in C++, thank you very much!

**Comment by joerowell** [comment]
To add to Shi's point: whilst such an algorithm doesn't exist in fplll, there are theoretical variants of LLL that work for any norm. These include the work of [Lovasz and Scarf](https://www.jstor.org/stable/3689761), and there's also a [bachelor's thesis](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdfdoi=5b9ca385be2d990381d3e9b0cf9386bb11e790d0) on the topic too. 

At a glance, both algorithms replace size-reduction with some kind of optimisation function that minimises the infinity norm. Thus, if you need something quickly you're likely to have better results implementing the algorithm in something like Sage, which already ships with such tools. I'd imagine that adding such a solver to fplll is out of scope, and so it's likely something that'll never be supported by fplll.

**Comment by zlhlovelattice** [comment]
Thank you for your answer, you mean that it is impossible for me to solve the LLL under the infinite norm metric by modifying the code in the fplll library, but I can try to do it in the Sagemath library, right?

> To add to Shi's point: whilst such an algorithm doesn't exist in fplll, there are theoretical variants of LLL that work for any norm. These include the work of [Lovasz and Scarf](https://www.jstor.org/stable/3689761), and there's also a [bachelor's thesis](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdfdoi=5b9ca385be2d990381d3e9b0cf9386bb11e790d0) on the topic too.
> 
> At a glance, both algorithms replace size-reduction with some kind of optimisation function that minimises the infinity norm. Thus, if you need something quickly you're likely to have better results implementing the algorithm in something like Sage, which already ships with such tools. I'd imagine that adding such a solver to fplll is out of scope, and so it's likely something that'll never be supported by fplll.

**Comment by joerowell** [comment]
> Thank you for your answer, you mean that it is impossible for me to solve the LLL under the infinite norm metric by modifying the code in the fplll library, but I can try to do it in the Sagemath library, right?

Yes, I recommend trying to do this in Sagemath instead.
