### ISSUE TITLE
Mixed style of Header inclusion

### ISSUE THREAD

**Issue by alxiong** [fplll/fplll#527]
I'm in the process of migrating build from libtool to cmake, and got bit confused with mixed styles of header inclusion.

Sometimes we see relative path "../defs.h", sometimes library root path "fplll/defs.h", sometimes system path <fplll/defs.h>

And is the assumption that some header files are installed into {prefix}/include first before I can build libfplll an important one? 

Would like to get clarifications on the reason behind this. Or is it just legacy issue and could all be refactored to using relative path?

**Comment by malb** [comment]
I don't think there's a policy here, it just organically grew this way and could/should be refactored :) 

PS: Personally speaking, I'd be less inclined to accept CMake PR than a refactoring PR.

**Comment by alxiong** [comment]
Got it, thanks for the clarification. 👍🏼
