### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by xrmzp** [fplll/fplll#53]
Is fplll parallelizable with Intel Thread Building Blocks (TBB)?

I have tried parallel run of BKZ reduction using TBB.
My code is basically as follows:
serial code: 
```
for (int i = 0; i < num; i++) {
    IntMatrix B(40,40);
    B.gen_uniform(40);
    bkzReduction(B, 20);
 }
```
parallel code:
```
void f() {
    IntMatrix B(40,40);
    B.gen_uniform(40);
    bkzReduction(B, 20);
} 
paralle_for(blocked_range<int> (0, num), f());
```

It only works for very small num, say 5.
When I increase num to 8, I can observe the segmentation fault sometimes.
After debugging, the error seems to happen inside the enumeration step of BKZ.
It reports that in the function Enumeration::enumerate(), there is a double free() or memory corruption.

BTW: when I use LLL reduction instead of BKZ, it seems fine so far.

**Comment by malb** [comment]
That seems plausible. Enumeration uses global variables (everything is static) and hence probably isn't thread safe.

**Comment by xrmzp** [comment]
Hi, malb. Thank you for your prompt response.

**Comment by malb** [comment]
Closing, see #147 for follow up
