### ISSUE TITLE
gen_ntrulike is misleading

### ISSUE THREAD

**Issue by malb** [fplll/fplll#63]
Users experimenting with our NTRU-like matrices expect them to have unusually short vectors,  but they don't (by construction). We should clarify this in the documentation at least:

```
template<class ZT> inline void ZZ_mat<ZT>::gen_ntrulike(int bits,int q) {
  int i, j, k;
  Z_NR<ZT> * h=new Z_NR<ZT>[d];

  for (i=0; i<d; i++)
    h[i].randb(bits);
  
  for (i=0; i<d; i++)    {
      for (j=0; j<i; j++)
        matrix[i][j] = 0;
      matrix[i][i] = 1;
      for (j=i+1; j<d; j++)
        matrix[i][j] = 0;
    }

  for (i=d; i<r; i++)
    for (j=0; j<d; j++)
      matrix[i][j] = 0;

  for (i=d; i<r; i++)   {
      for (j=d; j<i; j++)
        matrix[i][j] = 0;
      matrix[i][i] = q;
      for (j=i+1; j<c; j++)
        matrix[i][j] = 0;
    }

  for (i=0; i<d; i++)
    for (j=d; j<c; j++)   { 
        k = j+i;
        while (k>=d)k-=d;
        matrix[i][j] = h[k];
      }

  delete[] h;
}
```

**Comment by lducas** [comment]
Hi Martin,

sorry, this is not what I meant: on the contrary, I was expecting those to basically have shortest vectors length given by the Gaussian Heuristic, and I experimented q very wide variance around that behavior. 

Typically I would expect a range [90%,110%] for dimension, say 60 or 80. Instead I got something like [10%,150%].

**Comment by malb** [comment]
Ha, okay, then I subsumed your bug report under my grievances, sorry. Mhh, if h is constructed as rotations from just one vectors, perhaps the chances of hitting a basis with a particularly small/big basis increase, i.e. there is less randomness to even out the effects … he said wildly guessing?

**Comment by malb** [comment]
Looks like this is really an artefact of how these lattices behave. I just ran `python ntrulike.py -d 24 -w 16 -t 25` with [ntrulike.py](https://gist.github.com/1e0b55a382be4007c27d29fcc77bf6f0) and got

```
d: 24, workers: 16, tasks: 256
rot done 100.00%
mne done 100.00%
rnd done 100.00%
λ_1(rot):: min:      8749.16, avg:     53582.55, max:     64690.51
λ_1(mne):: min:      5589.97, avg:     53354.06, max:     64633.44
λ_1(rnd):: min:     52747.27, avg:     58052.21, max:     60635.29
```

**Comment by lducas** [comment]
Thanks Martin, 
so, according to your experiments, it is not related to th rotation, but just the shape in 2x2 blocks ?

Anyway, I'd guess my only suggestion would be to include at least generation of square matrices with typical random sv length, like the Darmstadt challenges.

**Comment by malb** [comment]
Yep, `rot` and `mne` are rotations, `mne` is my reimplementation to make sure it's not some weirdness in `gen_ntrulike` causing it. `rnd` should be what you're asking for, right?

**Comment by lducas** [comment]
Yes, rnd is equivalent to `nutrulike2` option, right ?

**Comment by malb** [comment]
No, [gen_ntrulike2](https://github.com/dstehle/fplll/blob/master/src/matrix.cpp#L331) essentially transposes the matrix, it's still rotational; `rnd` puts a uniform matrix above `qI`.

**Comment by shi-bai** [comment]
Hi,

I don't know why the "NTRU-like" leads to a usvp problem. For the 8749.16 matrix, the norms of BKZ-40 reduced basis are follows (nthrow, norm[nthrow])

0 8749.15767374208
1 62443.6880236906
2 64081.0981803527
3 64546.5180625570
4 67359.9219566056
5 71479.3083346502
6 68356.8940195501
7 63488.4142344097
8 72379.9849682217
9 67750.0202066390
10 69254.8274418470
11 70454.9298488048
12 78375.2522802957
13 68272.4526145062
14 78328.8316011416
15 72128.3964468918
16 75034.2869227129
17 67768.3700113851
18 67734.3069943142
19 68314.0010100419
20 72427.8288090980
21 77178.5679317775
22 64961.1115668444
23 71288.6781754298
24 64905.2765343466
25 74542.4225122849
26 72147.8296693670
27 72653.7263049873
28 80463.2157324078
29 71680.1684707842
30 72465.7101531476
31 77334.9053920673
32 77344.6893716692
33 73231.8311118874
34 82915.2808111991
35 79173.5586796501
36 82386.2568636299
37 68435.3841225429
38 69488.4966307374
39 71554.0152332488
40 69692.6644202961
41 81305.4132392180
42 72067.3081084620
43 78791.0049180742
44 65934.5122678556
45 81055.3023065117
46 86820.9859999298
47 145605.706217167

Attached matrix:
[ntru_test48.txt](https://github.com/dstehle/fplll/files/204357/ntru_test48.txt)

It seems that if we barely break the rotation (thanks to Martin's code), e.g. I added this like to ,
    A[0,2*d-1] = randint(0, 2**bits-1)
function ntru_like() after generating the matrix A. This just breaks a little bit on the rotation on the h part. The same python ntrulike.py -d 24 -w 16 -t 256 gives,

python ntrulike.py -d 24 -w 8 -t 256

d: 24, workers: 8, tasks: 256
rot done 100.00%
mne done 100.00%
rnd done 100.00%
λ_1(rot):: min:     49139.98, avg:     58099.15, max:     61055.42
λ_1(mne):: min:      5589.97, avg:     53354.06, max:     64633.44
λ_1(rnd):: min:     52747.27, avg:     58052.21, max:     60635.29

It seems indeed the rotation in h is the reason(?!)

For the naming, I think it will be more clear if there are two functions coming in pair: "NTRU" and "NTRU-like". Then we might be able to distinguish them. The  gen_ntrulike2 is a symmetric

**Comment by lducas** [comment]
Could it be that it is an (accidental) composite ring attack [Gentry]. You
are using cyclic matrix right ? Well, X^d - 1 tends to not be a prime
polynomial...

2016-04-05 14:19 GMT+02:00 shi-bai <notifications@github.com>:

**Comment by malb** [comment]
Mhh, changing `my_ntru_like` indeed takes care of some of the discrepancy:
```
def my_ntru_like(d, bits=30, q=1073741789):
    A = IntegerMatrix.random(d, "ntrulike", bits=bits, q=q)
    B = IntegerMatrix.random(d, "uniform", bits=bits)
    for i in range(d):
        for j in range(d):
            k = (i+j)%d
            A[i, d+k] = B[0, j]
        for j in range(i):
            A[i,d+j] = -A[i,d+j]
    return A
```

```
(fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 20 -w 16 -t 256
d: 20, workers: 16, tasks: 256
rot done 100.00%
mne done 100.00%
rnd done 100.00%
λ_1(rot):: min:      7194.55, avg:     51477.58, max:     61061.59
λ_1(mne):: min:     40419.41, avg:     57430.94, max:     61297.76
λ_1(rnd):: min:     48159.25, avg:     53457.16, max:     56323.45
(fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 22 -w 16 -t 256
d: 22, workers: 16, tasks: 256
rot done 100.00%
mne done 100.00%
rnd done 100.00%
λ_1(rot):: min:      2547.63, avg:     54331.47, max:     62823.43
λ_1(mne):: min:     21883.62, avg:     58899.04, max:     62760.42
λ_1(rnd):: min:     46541.14, avg:     55834.74, max:     58982.57
(fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 24 -w 16 -t 256
d: 24, workers: 16, tasks: 256
rot done 100.00%
mne done 100.00%
rnd done 100.00%
λ_1(rot):: min:      8749.16, avg:     53582.55, max:     64690.51
λ_1(mne):: min:     55727.14, avg:     61781.15, max:     65198.80
λ_1(rnd):: min:     52747.27, avg:     58052.21, max:     60635.29
```

**Comment by shi-bai** [comment]
Hi Martin,

On Wed, Apr 6, 2016 at 6:06 PM, Martin Albrecht
<notifications@github.com> wrote:
>
> Mhh, changing my_ntru_like indeed takes care of some of the discrepancy:
>
> def my_ntru_like(d, bits=30, q=1073741789):
>     A = IntegerMatrix.random(d, "ntrulike", bits=bits, q=q)
>     B = IntegerMatrix.random(d, "uniform", bits=bits)
>     for i in range(d):
>         for j in range(d):
>             k = (i+j)%d
>             A[i, d+k] = B[0, j]
>         for j in range(i):
>             A[i,d+j] = -A[i,d+j]
>     return A
>
> (fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 20 -w 16 -t 256
> d: 20, workers: 16, tasks: 256
> rot done 100.00%
> mne done 100.00%
> rnd done 100.00%
> λ_1(rot):: min:      7194.55, avg:     51477.58, max:     61061.59
> λ_1(mne):: min:     40419.41, avg:     57430.94, max:     61297.76
> λ_1(rnd):: min:     48159.25, avg:     53457.16, max:     56323.45
> (fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 22 -w 16 -t 256
> d: 22, workers: 16, tasks: 256
> rot done 100.00%
> mne done 100.00%
> rnd done 100.00%
> λ_1(rot):: min:      2547.63, avg:     54331.47, max:     62823.43
> λ_1(mne):: min:     21883.62, avg:     58899.04, max:     62760.42
> λ_1(rnd):: min:     46541.14, avg:     55834.74, max:     58982.57
> (fpylll)malb@strombenzin:: ~ > python ntrulike.py -d 24 -w 16 -t 256
> d: 24, workers: 16, tasks: 256
> rot done 100.00%
> mne done 100.00%
> rnd done 100.00%
> λ_1(rot):: min:      8749.16, avg:     53582.55, max:     64690.51
> λ_1(mne):: min:     55727.14, avg:     61781.15, max:     65198.80
> λ_1(rnd):: min:     52747.27, avg:     58052.21, max:     60635.29

I've got something similar using anti-cyclic lattices (denoted mne2).

python ntrulike.py -d 24 -w 8 -t 256
d: 24, workers: 8, tasks: 256
rot done 100.00%
mne done 100.00%
mne2 done 100.00%
rnd done 100.00%
λ_1(rot):: min:      8749.16, avg:     53582.55, max:     64690.51
λ_1(mne):: min:      5589.97, avg:     53354.06, max:     64633.44
λ_1(mne2):: min:     53134.42, avg:     61941.23, max:     65283.96
λ_1(rnd):: min:     52145.24, avg:     57940.42, max:     61037.80

Cheers,
Shi

**Comment by shi-bai** [comment]
Can we close this?

**Comment by lducas** [comment]
Do as you feel... I'm just afraid people pays draw incorrect conclusion
when experimenting with those (eg. http://eprint.iacr.org/2016/385)

--L

**Comment by malb** [comment]
We could fix it up during fplll days?

**Comment by shi-bai** [comment]
Do we want gen_ntrulike and gen_ntru both?

Shi

**Comment by shi-bai** [comment]
perhaps we will have a true gen_ntru there?

**Comment by dstehle** [comment]
OK. I got it. 
We could change fplll's ntru-like so that h(1) = 0. That should kill this odd-ness concerning the Gaussian heuristic. 

I will add a disclaimer in the documentation saying that h is not the quotient of two tiny polynomials. 

Shall we keep or kill option 'N' (the reordering of the vectors produced by option 'n')?
