### ISSUE TITLE
problem using fplll as a library with g++ 6.1

### ISSUE THREAD

**Issue by sfilip** [fplll/fplll#65]
Hi! Using fplll as a library with g++ version 6.1 fails on my machine when compiling with the C++11 and C++14 standards. This is caused by the use of hexadecimal floating point constants in the src/dpe.h file (lines 186-192), which are not officially recognized as being standard C++ (they will be in C++17 however!), but are part of the C99 and C11 standards. The error message is: _error: exponent has no digits_

Before updating to g++ 6.1 I did not have this problem (even when using the -std=c++11 and -std=c++14 flags). Hexadecimal floats in g++ are now available **only** as extensions, by using -std=gnu89, -std=gnu++11 or -std=gnu++14 (now, the default flag).

Maybe other users should be aware of this if they switch to a newer g++ version.

**Comment by dstehle** [comment]
Hi Silviu,
The bug seems gone. Can you please check? 

D.

**Comment by shi-bai** [comment]
maybe we now use std=gnu++11 ?

**Comment by sfilip** [comment]
Hi!

I just checked, but I'm still having the same issue. I can't compile it using -std=c++11. If I compile it with a -std=gnu++xx flag, then I also have to link to it using a similar flag. -std=c++11 doesn't work.

Silviu

**Comment by sfilip** [comment]
Here is also the error message that I get when compiling the library:

In file included from nr/../defs.h:56:0,
                 from nr/nr.h:8,
                 from nr/numvect.h:19,
                 from nr/matrix.h:21,
                 from wrapper.h:21,
                 from fplll.cpp:18:
nr/../nr/dpe.h:186:10: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
          ^~~~
nr/../nr/dpe.h:186:18: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                  ^~~~
nr/../nr/dpe.h:186:26: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                          ^~~~
nr/../nr/dpe.h:186:34: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                                  ^~~~
nr/../nr/dpe.h:186:42: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                                          ^~~~
nr/../nr/dpe.h:186:50: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                                                  ^~~~
nr/../nr/dpe.h:186:58: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                                                          ^~~~
nr/../nr/dpe.h:186:66: error: exponent has no digits
   0x1P0, 0x1P-1, 0x1P-2, 0x1P-3, 0x1P-4, 0x1P-5, 0x1P-6, 0x1P-7, 0x1P-8,
                                                                  ^~~~
nr/../nr/dpe.h:187:3: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
   ^~~~
nr/../nr/dpe.h:187:11: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
           ^~~~
nr/../nr/dpe.h:187:20: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                    ^~~~
nr/../nr/dpe.h:187:29: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                             ^~~~
nr/../nr/dpe.h:187:38: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                                      ^~~~
nr/../nr/dpe.h:187:47: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                                               ^~~~
nr/../nr/dpe.h:187:56: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                                                        ^~~~
nr/../nr/dpe.h:187:65: error: exponent has no digits
   0x1P-9, 0x1P-10, 0x1P-11, 0x1P-12, 0x1P-13, 0x1P-14, 0x1P-15, 0x1P-16,
                                                                 ^~~~
nr/../nr/dpe.h:188:3: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
   ^~~~
nr/../nr/dpe.h:188:12: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
            ^~~~
nr/../nr/dpe.h:188:21: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                     ^~~~
nr/../nr/dpe.h:188:30: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                              ^~~~
nr/../nr/dpe.h:188:39: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                                       ^~~~
nr/../nr/dpe.h:188:48: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                                                ^~~~
nr/../nr/dpe.h:188:57: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                                                         ^~~~
nr/../nr/dpe.h:188:66: error: exponent has no digits
   0x1P-17, 0x1P-18, 0x1P-19, 0x1P-20, 0x1P-21, 0x1P-22, 0x1P-23, 0x1P-24,
                                                                  ^~~~
nr/../nr/dpe.h:189:3: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
   ^~~~
nr/../nr/dpe.h:189:12: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
            ^~~~
nr/../nr/dpe.h:189:21: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                     ^~~~
nr/../nr/dpe.h:189:30: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                              ^~~~
nr/../nr/dpe.h:189:39: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                                       ^~~~
nr/../nr/dpe.h:189:48: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                                                ^~~~
nr/../nr/dpe.h:189:57: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                                                         ^~~~
nr/../nr/dpe.h:189:66: error: exponent has no digits
   0x1P-25, 0x1P-26, 0x1P-27, 0x1P-28, 0x1P-29, 0x1P-30, 0x1P-31, 0x1P-32,
                                                                  ^~~~
nr/../nr/dpe.h:190:3: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
   ^~~~
nr/../nr/dpe.h:190:12: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
            ^~~~
nr/../nr/dpe.h:190:21: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                     ^~~~
nr/../nr/dpe.h:190:30: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                              ^~~~
nr/../nr/dpe.h:190:39: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                                       ^~~~
nr/../nr/dpe.h:190:48: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                                                ^~~~
nr/../nr/dpe.h:190:57: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                                                         ^~~~
nr/../nr/dpe.h:190:66: error: exponent has no digits
   0x1P-33, 0x1P-34, 0x1P-35, 0x1P-36, 0x1P-37, 0x1P-38, 0x1P-39, 0x1P-40,
                                                                  ^~~~
nr/../nr/dpe.h:191:3: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
   ^~~~
nr/../nr/dpe.h:191:12: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
            ^~~~
nr/../nr/dpe.h:191:21: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                     ^~~~
nr/../nr/dpe.h:191:30: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                              ^~~~
nr/../nr/dpe.h:191:39: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                                       ^~~~
nr/../nr/dpe.h:191:48: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                                                ^~~~
nr/../nr/dpe.h:191:57: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                                                         ^~~~
nr/../nr/dpe.h:191:66: error: exponent has no digits
   0x1P-41, 0x1P-42, 0x1P-43, 0x1P-44, 0x1P-45, 0x1P-46, 0x1P-47, 0x1P-48,
                                                                  ^~~~
nr/../nr/dpe.h:192:3: error: exponent has no digits
   0x1P-49, 0x1P-50, 0x1P-51, 0x1P-52, 0x1P-53};
   ^~~~
nr/../nr/dpe.h:192:12: error: exponent has no digits
   0x1P-49, 0x1P-50, 0x1P-51, 0x1P-52, 0x1P-53};
            ^~~~
nr/../nr/dpe.h:192:21: error: exponent has no digits
   0x1P-49, 0x1P-50, 0x1P-51, 0x1P-52, 0x1P-53};
                     ^~~~
nr/../nr/dpe.h:192:30: error: exponent has no digits
   0x1P-49, 0x1P-50, 0x1P-51, 0x1P-52, 0x1P-53};
                              ^~~~
nr/../nr/dpe.h:192:39: error: exponent has no digits
   0x1P-49, 0x1P-50, 0x1P-51, 0x1P-52, 0x1P-53};
                                       ^~~~
Makefile:802: recipe for target 'fplll.lo' failed

**Comment by shi-bai** [comment]
Thanks Silviu for the test again. I removed those hex flp in my fork
https://github.com/shi-bai/fplll

Could you please test the fplll in my fork to see if it works now? If so, we could merge the changes to the main repo. Thanks :)

**Comment by sfilip** [comment]
No problem, Shi! I'm able to compile it now :). There is still one minor problem. When I try to link against it, it gives me an error:

In file included from /usr/local/include/fplll/bkz.h:23:0,
                 from /usr/local/include/fplll/fplll.h:27,
                 from /usr/local/include/fplll.h:1:
/usr/local/include/fplll/enum/enumerate.h:24:39: fatal error: fplll/enum/enumerate_base.h: No such file or directory
 #include <fplll/enum/enumerate_base.h>

When using make install with default parameters, the enumerate_base.h header is not copied to /usr/local/include/fplll/enum, making the linking process fail (i'm using fplll as a shared library). I'm able to get around it by manually copying the file there, though.

**Comment by shi-bai** [comment]
Silviu, thanks for the test again and the bug report. It seems that we need
enum/enumerate_base.h
in nobase_include_fplll_HEADERS in Makefile.am

I added that in the current fplll git. Could you please try again? Tks :)

**Comment by sfilip** [comment]
Yes, that solved the last error! Once you add the changes from your fork, I'll check again to see if the hexadecimal float error is gone as well.

**Comment by shi-bai** [comment]
Hi Silviu, thanks! Could you try to the current git version?

**Comment by sfilip** [comment]
Hi Shi! Everything seems to be working fine now on my machine with the current git version.
