### ISSUE TITLE
Where are new releases to be seen?

### ISSUE THREAD

**Issue by SnarkBoojum** [fplll/fplll#66]
According to README.md, one should learn about new releases checking an URI at Damien Stehle's ENS Lyon page -- but that one is a redirect on github, where there are no actual releases!

Could you document it better and **tag** releases on github, so I can keep my Debian package up to date?

Thanks!

**Comment by malb** [comment]
Hi, we don't have released an releases since fplll 4.0.4. But you're right this needs to be worked out eventually.

**Comment by SnarkBoojum** [comment]
Hmmm... sage has  a 20160331 version... did they just take a snapshot?

**Comment by malb** [comment]
Yep, I did that.

**Comment by SnarkBoojum** [comment]
My Debian package still is 4.0.4 and I'm wondering if it's compatible with what sage uses. What was worth doing a snapshot and not a release?

**Comment by malb** [comment]
The API have changed so upgrading to post 4.0.4 will be required for Sage to work. A snapshot is easy to do, a release requires the whole team to agree on that we are ready for a new release. We have a workshop coming up, this might be a good opportunity to cut a new release.

**Comment by SnarkBoojum** [comment]
Ok, then let's wait for the new release. (Though I don't exactly get how the snapshot could manage to be both worth it for sage and not worth a release for all distributions...)

**Comment by dstehle** [comment]
README.md now states that "New releases will be announced on https://groups.google.com/forum/#!forum/fplll-devel."

Shall we close this?

**Comment by malb** [comment]
Agreed.
