### ISSUE TITLE
gen_foo() for instance generation should accept larger moduli

### ISSUE THREAD

**Issue by malb** [fplll/fplll#70]
Restricting moduli to machine integers can be quite limiting.

**Comment by dstehle** [comment]
Are you referring to ntru?

**Comment by malb** [comment]
Yep, and NTRULike2

**Comment by dstehle** [comment]
I've fixed it in my branch.ill upload it tomorrow.

D.
Le 21 juin 2016 5:48 PM, "Martin Albrecht" <notifications@github.com> a
écrit :

**Comment by dstehle** [comment]
I think this is now fixed
