### ISSUE TITLE
Quadruple precision

### ISSUE THREAD

**Issue by dstehle** [fplll/fplll#77]
Shall we still use QD floating-point numbers or replace it with something more standard?

**Comment by malb** [comment]
The proposal is to drop `qd_real` (replaced by `mpfr_t`) but to keep using `dd_real`?

If so, we should document the performance reasons why we do this in this ticket. @shi-bai want to post your timings here?

**Comment by shi-bai** [comment]
Here is a timing summary: 
1) for basic arithmetic, I have got, 
--------------
Timing double
-------------
   add:   0.000279 us 3582.2713 mop/s
   mul:   0.000348 us 2872.5727 mop/s
   div:   0.003663 us  273.0157 mop/s
--------------
Timing dd_real
--------------
   add:   0.002847 us  351.2479 mop/s
   mul:   0.005177 us  193.1585 mop/s
   div:   0.011143 us   89.7463 mop/s
--------------
Timing qd_real
--------------
   add:   0.036100 us   27.7006 mop/s
   mul:   0.070247 us   14.2354 mop/s
   div:   0.296834 us    3.3689 mop/s
--------------
Timing mpfr c++ (212 bit)
--------------
   add:   0.022815 us   43.8310 mop/s
   mul:   0.052974 us   18.8773 mop/s
   div:   0.110046 us    9.0871 mop/s

Also to compare qd and mpfr of similar precision, we checked this in FPLLL, e.g. with attached example, 

time ./fplll -a lll -m proved  -f mpfr -p 212 -of '' -v  test_qd_mpfr
real	5m37.472s
user	5m37.296s

time ./fplll -a lll -m proved  -f qd -of '' -v  test_qd_mpfr 
real	6m27.772s
user	6m27.596s

This was check also with ./latticegen r 200 2000 and with option -f for qd and mpfr.

[test_qd_mpfr.txt](https://github.com/fplll/fplll/files/331863/test_qd_mpfr.txt)

**Comment by shi-bai** [comment]
Updated this ticket with the current mpfr (SVN r11586 or mpfr4). Some timings from Paul Zimmermann suggest that (for fplll run on input 200 dim input of  -a lll -m proved -f mpfr -p 106/212 ), the 

> - mpfr4 is faster then mpfr3 by about 20% for 106 bits and 7% for 212 bits
> - mpfr4 with 212 bits is 15% faster than qd (and mpfr3 was already faster)
> - mpfr4 with 106 bits is only 63% slower than dd

In the current FPLLL wrapper, we start to use mpfr right after double-double; the exact precision allocated for mpfr might be smaller than 212; thus the gain (using mpfr4 v.s. mpfr 3) might be slightly more than 7%. (But this accounts only for the time for the mpfr part, not the the total running-time in wrapper as it switches various precisions.)
