### ISSUE TITLE
more lattice generators

### ISSUE THREAD

**Issue by malb** [fplll/fplll#98]
We use

```python
def make_integer_matrix(n, q=None):
    A = IntegerMatrix(n, n)

    if q is None:
        q = prime_list[n]

    A[0, 0] = q
    for i in range(1, n):
        A[i, 0] = randint(0, q-1)
        A[i, i] = 1
```

for our benchmarketing/parameter estimation in another project. Maybe this should be added under the appropriate name to `fplll`?

**Comment by dstehle** [comment]
This is very close to option r. The behaviour should be similar.
Is there a reason you do not use option r in your other project? 

Also, isn't it a special case of the q-ary suggestion of the other discussion thread?

**Comment by malb** [comment]
Yep, it's close `r` but it's square, hence a bit nicer. Indeed, I thought of this because of the q-ary thing.

**Comment by dstehle** [comment]
I think it's now done, in dev branch
